"""
AI2 — batch 4 mo rong KB: viet tay 15 doc/pattern cho 3 pattern tiep theo
(closure_loop_var:24, counter_no_atomic:24, callback_hell:24). Moi doc la 1
tinh huong code CU THE khac nhau that su, khong dung khuon cau lap lai.

Chay: python add_batch4_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ============= CLOSURE_LOOP_VAR (15 doc) =============
    {"id": "js-b4-clv-001", "title": "Closure Loop Var: Dang Ky Nhieu Event Listener DOM Trong Vong Lap Voi Index Sai",
     "content": "for (var i = 0; i < buttons.length; i++) { buttons[i].addEventListener('click', function() { console.log('Button ' + i + ' clicked') }) } — moi button khi click deu log cung 1 gia tri i (bang buttons.length, vi vong lap da chay xong truoc khi user kip click) thay vi index rieng cua tung button — do var khong tao block scope, tat ca closure trong addEventListener chia se chung 1 bien i trong pham vi function bao ngoai.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-002", "title": "Closure Loop Var: Tao Nhieu Timer setTimeout De Delay Xu Ly Tung Item Nhung In Sai Gia Tri",
     "content": "for (var idx = 0; idx < tasks.length; idx++) { setTimeout(function() { processTask(tasks[idx]) }, idx * 1000) } — moi lan setTimeout thuc thi (sau khi vong lap for da chay het), tasks[idx] deu doc idx bang gia tri cuoi cung (tasks.length), gay loi 'tasks[tasks.length] is undefined' hoac xu ly nham item cuoi cung nhieu lan thay vi tung item rieng theo dung thu tu delay du kien.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-003", "title": "Closure Loop Var: Tao Mang Cac Ham Promise Executor Trong Vong Lap For",
     "content": "var promises = []; for (var i = 0; i < urls.length; i++) { promises.push(new Promise(function(resolve) { fetch(urls[i]).then(function(res) { resolve({ index: i, data: res }) }) })) } — moi Promise trong mang khi resolve deu gan index bang gia tri cuoi cung cua i (urls.length), khien code doc ket qua tra ve khong the phan biet duoc response nao tuong ung voi url nao trong danh sach ket qua tra ve tu Promise.all().",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-004", "title": "Closure Loop Var: Dang Ky Nhieu WebSocket Message Handler Cho Cac Room Khac Nhau Trong For-Loop",
     "content": "for (var i = 0; i < rooms.length; i++) { sockets[i].on('message', function(data) { handleRoomMessage(rooms[i], data) }) } — tat ca handler khi nhan message deu goi handleRoomMessage voi rooms[rooms.length] (undefined) thay vi room tuong ung voi socket dang nhan — moi tin nhan tu bat ky room nao deu bi xu ly sai, thuong dan den crash do truy cap property tren rooms[undefined].",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-005", "title": "Closure Loop Var: Tao Nhieu Worker Thread Voi ID Trong Vong Lap Va Log Ket Qua",
     "content": "for (var i = 0; i < numWorkers; i++) { var worker = new Worker('./worker.js'); worker.on('message', function(result) { console.log('Worker ' + i + ' result: ' + result) }) } — moi worker khi tra ve ket qua deu log cung 1 so worker (numWorkers, vi vong lap da chay xong truoc khi worker dau tien kip gui message), khien log hoan toan sai lech, khong the theo doi worker nao dang lam viec gi trong he thong giam sat.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-006", "title": "Closure Loop Var: Xay Dung Mang Cac Ham Validator Trong Vong Lap De Dung Sau Nay",
     "content": "var validators = []; for (var i = 0; i < rules.length; i++) { validators.push(function(value) { return applyRule(rules[i], value) }) } — khi validators[0](someValue) duoc goi sau nay, no van doc rules[rules.length] (undefined) thay vi rules[0] nhu ten bien validators[0] goi y — toan bo mang validator deu ap dung sai rule (hoac throw loi do rules[undefined]), bug chi lo ra khi validator thuc su duoc goi, xa noi khai bao vong lap.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-007", "title": "Closure Loop Var: Animation Frame Callback Trong Vong Lap De Ve Nhieu Object Canvas",
     "content": "for (var i = 0; i < shapes.length; i++) { requestAnimationFrame(function() { drawShape(shapes[i], ctx) }) } — requestAnimationFrame lui thoi diem thuc thi callback sang frame tiep theo (bat dong bo), luc do vong lap for da chay xong, tat ca callback deu doc shapes[shapes.length] (undefined) — canvas khong ve duoc hinh nao hoac throw loi khi drawShape() nhan tham so undefined.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-008", "title": "Closure Loop Var: Dang Ky Cron Job Rieng Cho Tung Config Trong Vong Lap",
     "content": "for (var i = 0; i < scheduledJobs.length; i++) { cron.schedule(scheduledJobs[i].cronTime, function() { runJob(scheduledJobs[i].config) }) } — moi lan bat ky cron job nao trong so nay kich hoat (co the la vai gio sau khi server khoi dong, vong lap for da chay xong tu lau), tat ca deu goi runJob voi scheduledJobs[scheduledJobs.length].config (undefined), gay crash lien tuc moi khi cron trigger thay vi chay dung config du kien.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-009", "title": "Closure Loop Var: Tao Nhieu Interval De Poll Trang Thai Cua Cac Job Khac Nhau",
     "content": "for (var i = 0; i < jobIds.length; i++) { var interval = setInterval(function() { checkJobStatus(jobIds[i], function(done) { if (done) clearInterval(interval) }) }, 2000) } — ca 2 bien 'i' va 'interval' deu bi loi tuong tu: jobIds[i] luon la undefined (jobIds.length) VA bien 'interval' ben trong closure cung chi tro ve gia tri cuoi cung (interval cua job cuoi), khien clearInterval() go nham interval cua job khac, cac interval con lai chay mai ma khong bao gio duoc dung.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-010", "title": "Closure Loop Var: Xu Ly Callback Xac Nhan Thanh Toan Cho Tung Don Hang Trong Vong Lap Batch",
     "content": "for (var i = 0; i < orders.length; i++) { paymentGateway.charge(orders[i].amount, function(err, result) { if (err) handleFailedOrder(orders[i]) else markOrderPaid(orders[i]) }) } — callback cua paymentGateway.charge() la bat dong bo, luc no chay thi vong lap for da hoan tat tu lau — moi don hang (bat ke thanh cong hay that bai) deu bi markOrderPaid()/handleFailedOrder() goi voi orders[orders.length] (undefined), toan bo he thong xu ly thanh toan tra loi sai don hang.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-011", "title": "Closure Loop Var: Dang Ky File Watcher Rieng Cho Tung Thu Muc Trong Vong Lap Khoi Tao",
     "content": "for (var i = 0; i < watchedDirs.length; i++) { fs.watch(watchedDirs[i], function(eventType, filename) { console.log('Change in ' + watchedDirs[i] + ': ' + filename) }) } — moi thay doi file trong BAT KY thu muc nao duoc theo doi deu log cung 1 duong dan sai (watchedDirs[watchedDirs.length], undefined) — he thong giam sat file khong the phan biet duoc thay doi den tu thu muc nao, log hoan toan vo nghia cho muc dich debug/audit.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-012", "title": "Closure Loop Var: Tao Nhieu HTTP Request Voi Retry Callback Rieng Trong Vong Lap",
     "content": "for (var i = 0; i < endpoints.length; i++) { http.get(endpoints[i], function(res) { res.on('end', function() { console.log('Request to ' + endpoints[i] + ' done') }) }) } — closure long nhau (2 cap: callback cua http.get va callback cua 'end' event) deu tham chieu chung 1 bien i — ca 2 cap deu doc endpoints[endpoints.length] (undefined) khi thuc thi, log bao cao request toi 'undefined' cho tat ca endpoint, khong the biet request nao thanh cong request nao that bai.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-013", "title": "Closure Loop Var: Xay Dung Menu Dropdown Voi Handler Rieng Cho Tung Muc Trong Vong Lap DOM",
     "content": "for (var i = 0; i < menuItems.length; i++) { var el = document.createElement('li'); el.textContent = menuItems[i].label; el.onclick = function() { navigateTo(menuItems[i].route) }; menu.appendChild(el) } — click vao BAT KY muc menu nao deu dieu huong toi menuItems[menuItems.length].route (undefined), khien click vao muc nao cung bi loi 'Cannot read property route of undefined' hoac dieu huong sai trang, du el.textContent hien thi dung ten muc.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-014", "title": "Closure Loop Var: Dang Ky Handler Cho Nhieu Redis Pub/Sub Channel Trong Vong Lap Khoi Tao",
     "content": "for (var i = 0; i < channels.length; i++) { redisSubscriber.subscribe(channels[i]); redisSubscriber.on('message', function(channel, message) { if (channel === channels[i]) processChannelMessage(channel, message) }) } — dieu kien 'channel === channels[i]' luon so sanh voi channels[channels.length] (undefined), khong bao gio dung voi bat ky channel thuc te nao — toan bo logic processChannelMessage() khong bao gio duoc goi, message tu tat ca channel bi lang le bo qua ma khong co loi ro rang nao xuat hien.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},
    {"id": "js-b4-clv-015", "title": "Closure Loop Var: Tao Nhieu Test Case Dong Bang Trong Vong Lap For De Sinh Test Jest",
     "content": "for (var i = 0; i < testCases.length; i++) { test('case ' + i, function() { const result = runFunction(testCases[i].input); expect(result).toBe(testCases[i].expected) }) } — moi test case khi Jest thuc su chay (bat dong bo, sau khi toan bo file test da duoc doc va vong lap da chay xong) deu doc testCases[testCases.length] (undefined) — tat ca test case deu fail voi loi giong het nhau 'Cannot read property input of undefined', khong the biet test case cu the nao that su that bai trong logic goc.",
     "language": "javascript", "category": "patterns",
     "source": "Generated (batch4, dua tren mo ta closure_loop_var)", "url": "", "pattern_ids": ["closure_loop_var"]},

    # ============= COUNTER_NO_ATOMIC (15 doc) =============
    {"id": "js-b4-cna-001", "title": "Counter No Atomic: Dem So Luot View Bai Viet Bang Doc-Cong-Ghi Tren Redis Khong Dung INCR",
     "content": "async function recordView(postId) { const current = await redis.get('views:' + postId); const newCount = parseInt(current || 0) + 1; await redis.set('views:' + postId, newCount) } — nhieu request view bai viet dong thoi (bai viet dang trending) cung doc gia tri current gan nhu cung luc, moi request cong 1 roi ghi lai — nhieu luot view bi mat do cac lan ghi ghi de len nhau, view count hien thi thap hon nhieu so voi so luot truy cap thuc te.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-002", "title": "Counter No Atomic: Tang Bien Dem Job Da Hoan Thanh Trong Worker Pool Song Song",
     "content": "let completedJobs = 0; workers.forEach(w => w.on('done', () => { completedJobs = completedJobs + 1; if (completedJobs === totalJobs) onAllComplete() })) — bieu thuc 'completedJobs + 1' doc gia tri hien tai roi cong roi gan lai — neu 2 worker bao 'done' gan nhu dong thoi (JS don luong nen thuc te an toan trong truong hop don gian nay, NHUNG neu logic duoc chuyen sang dung SharedArrayBuffer + nhieu worker_threads that su chay song song, phep tang nay khong con atomic, dieu kien '=== totalJobs' co the khong bao gio dung du tat ca job da xong.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-003", "title": "Counter No Atomic: Dem So Luong Ve Con Lai Cho Su Kien Ban Ve Online Bang MongoDB Doc-Ghi Rieng",
     "content": "async function bookTicket(eventId) { const event = await db.events.findOne({ _id: eventId }); if (event.ticketsLeft > 0) { await db.events.updateOne({ _id: eventId }, { $set: { ticketsLeft: event.ticketsLeft - 1 } }); return true } return false } — 2 nguoi mua ve gan nhu dong thoi khi chi con 1 ve — ca 2 cung doc event.ticketsLeft là 1, ca 2 deu qua dieu kien kiem tra '> 0', ca 2 cung ghi ticketsLeft = 0 — ban duoc 2 ve trong khi chi co 1 ve, gay oversell that su cho khach hang.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-004", "title": "Counter No Atomic: Tang Diem Kinh Nghiem (XP) Nguoi Choi Tu Nhieu Nguon Su Kien Game Dong Thoi",
     "content": "let playerXP = { [userId]: 0 }; function addXP(userId, amount) { playerXP[userId] = playerXP[userId] + amount } onKillEnemy(() => addXP(userId, 10)); onCompleteQuest(() => addXP(userId, 50)) — neu nguoi choi giet quai VA hoan thanh quest gan nhu dong thoi (2 event handler trigger gan nhu cung luc trong 1 frame game), thao tac doc-cong-ghi khong atomic co the khien 1 trong 2 lan cong XP bi mat, tong diem kinh nghiem cuoi cung thap hon so voi tong 2 hanh dong that su mang lai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-005", "title": "Counter No Atomic: Dem Retry Count Cho Job Trong Queue Bang Doc Truoc Ghi Sau Tren Database",
     "content": "async function retryJob(jobId) { const job = await db.jobs.findById(jobId); if (job.retryCount >= MAX_RETRIES) return markFailed(jobId); await db.jobs.update(jobId, { retryCount: job.retryCount + 1 }); return processJob(job) } — neu 2 worker cung nhan job nay do loi trong co che phan phoi hang doi (duplicate delivery), ca 2 cung doc retryCount cu, ca 2 cung ghi retryCount + 1 (gia tri giong nhau) — job co the duoc retry vuot qua MAX_RETRIES thuc te ma khong bi phat hien, gay vong lap retry vo han neu job luon that bai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-006", "title": "Counter No Atomic: Tang Bien Dem Active Connections Trong WebSocket Server De Gioi Han Tai",
     "content": "let activeConnections = 0; wss.on('connection', (ws) => { activeConnections++; if (activeConnections > MAX_CONN) { ws.close(); activeConnections--; return } ws.on('close', () => activeConnections--) }) — trong Node.js don luong doan nay thuc te an toan (khong co race that su vi khong co await xen giua), NHUNG neu server duoc scale ngang qua cluster module (nhieu process con), moi process co bien activeConnections RIENG — gioi han MAX_CONN thuc te ap dung tren MOI process thay vi toan cuc, tong so ket noi thuc te co the vuot xa MAX_CONN du dinh.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-007", "title": "Counter No Atomic: Dem So Diem Danh Hang Ngay Cua User Bang Doc-Kiem Tra-Ghi Tren PostgreSQL",
     "content": "async function checkIn(userId) { const user = await db.query('SELECT streak FROM users WHERE id = $1', [userId]); const newStreak = user.streak + 1; await db.query('UPDATE users SET streak = $1 WHERE id = $2', [newStreak, userId]) } — user bam nut diem danh 2 lan lien tiep rat nhanh (double-click hoac 2 tab), 2 request cung doc streak cu, ca 2 cung ghi streak + 1 (gia tri giong nhau thay vi +2) — user co the loi dung bug nay de kiem tra co tang duoc streak gian lan hay khong, hoac vo tinh mat 1 lan tang streak that su.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-008", "title": "Counter No Atomic: Tang Bien Dem Loi Lien Tiep De Trigger Circuit Breaker Trong Microservice",
     "content": "let consecutiveFailures = 0; async function callDownstream() { try { const res = await fetch(url); consecutiveFailures = 0; return res } catch (e) { consecutiveFailures = consecutiveFailures + 1; if (consecutiveFailures >= THRESHOLD) openCircuit(); throw e } } — nhieu request dong thoi cung goi callDownstream() khi downstream service dang gap su co, moi request that bai gan nhu dong thoi doc consecutiveFailures cu roi cong 1 — 1 so lan tang bi mat do ghi de, circuit breaker co the khong bao gio mo du service thuc te da that bai vuot nguong THRESHOLD, gay ton hai lan truyen loi tiep tuc toi service dang qua tai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-009", "title": "Counter No Atomic: Dem So Lan Su Dung Coupon Giam Gia Truoc Khi Vo Hieu Hoa",
     "content": "async function applyCoupon(code) { const coupon = await db.coupons.findOne({ code }); if (coupon.usedCount >= coupon.maxUses) return { error: 'Coupon het luot' }; await db.coupons.updateOne({ code }, { $set: { usedCount: coupon.usedCount + 1 } }); return { discount: coupon.discount } } — nhieu khach hang ap dung coupon gan nhu dong thoi luc coupon sap het luot (con 1 luot, 5 nguoi cung bam ap dung) — do doc-kiem tra-ghi khong atomic, ca 5 co the deu qua duoc dieu kien kiem tra va deu duoc ap dung giam gia, vuot xa maxUses da dat ra, gay thiet hai tai chinh cho doanh nghiep.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-010", "title": "Counter No Atomic: Tang Bien Dem Request Trong Sliding Window Rate Limiter Dung Bien Memory",
     "content": "const requestCounts = {}; function isAllowed(apiKey) { requestCounts[apiKey] = (requestCounts[apiKey] || 0) + 1; return requestCounts[apiKey] <= LIMIT } — trong middleware async (co await truoc doan check nay), 2 request tu cung apiKey gan nhu dong thoi cung doc gia tri cu cua requestCounts[apiKey], ca 2 cung tang len cung 1 gia tri (thay vi +1 roi +1 nua) — bo dem thuc te dem thieu so request that su, cho phep client vuot qua LIMIT da cau hinh.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-011", "title": "Counter No Atomic: Dem So Sao (Star/Like) Cua Repo Trong He Thong Cache Layer Truoc Khi Sync Database",
     "content": "let starCache = {}; function addStar(repoId) { starCache[repoId] = (starCache[repoId] || 0) + 1; scheduleSyncToDb(repoId) } — nhieu user bam star gan nhu dong thoi cho 1 repo dang trending (hang tram request/giay) — neu logic nay duoc chay tren nhieu instance server (khong dung Redis chung ma dung memory cache rieng tung instance), moi instance dem rieng, khi sync ve database co the ghi de len nhau, tong so sao cuoi cung thap hon nhieu so voi so lan bam that su.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-012", "title": "Counter No Atomic: Tang So Luong Item Trong Gio Hang Khi User Bam Nut '+' Lien Tuc Nhanh",
     "content": "app.post('/cart/increment', async (req, res) => { const cart = await getCart(req.sessionId); cart.items[req.body.productId].qty = cart.items[req.body.productId].qty + 1; await saveCart(cart); res.json(cart) }) — user bam nut '+' rat nhanh nhieu lan lien tiep (truoc khi request truoc kip hoan tat), cac request xen ke doc cung 1 gia tri qty cu — so luong san pham hien thi trong gio hang thap hon so lan user thuc su bam, gay trai nghiem 'bam khong an' kho chiu cho nguoi dung.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-013", "title": "Counter No Atomic: Dem So Luong Thong Bao Chua Doc Trong Badge Count Tren Nhieu Thiet Bi",
     "content": "async function incrementUnreadCount(userId) { const user = await db.users.findById(userId); await db.users.update(userId, { unreadCount: user.unreadCount + 1 }) } — user nhan 2 thong bao gan nhu dong thoi tu 2 nguon khac nhau (vi du 1 tin nhan va 1 luot follow moi cung luc) — 2 lan goi ham nay xen ke doc cung gia tri unreadCount cu, ket qua badge chi tang 1 thay vi 2, user thay so luong thong bao chua doc it hon thuc te tren icon app.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-014", "title": "Counter No Atomic: Tang Bien Dem So Luong Loi Parse Trong Batch Processing Log File Song Song",
     "content": "let parseErrors = 0; async function processLogFiles(files) { await Promise.all(files.map(async (f) => { try { await parseFile(f) } catch (e) { parseErrors = parseErrors + 1 } })) } console.log('Total errors: ' + parseErrors) — nhieu file duoc xu ly song song qua Promise.all, moi file loi gan nhu dong thoi cong vao parseErrors — trong Node.js don luong don gian nay thuc te an toan (khong co await xen giua doc va ghi), NHUNG neu logic tuong tu duoc port sang worker_threads that su song song de tang toc do xu ly file lon, tinh atomic se mat va so loi bao cao cuoi cung se thap hon thuc te.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},
    {"id": "js-b4-cna-015", "title": "Counter No Atomic: Dem So Luong Slot Con Trong He Thong Dat Cho Phong Hop Qua API",
     "content": "async function bookRoom(roomId, timeSlot) { const room = await db.rooms.findById(roomId); const slot = room.slots.find(s => s.time === timeSlot); if (slot.available > 0) { slot.available -= 1; await db.rooms.update(roomId, room); return true } return false } — 2 nhan vien dat cung 1 khung gio phong hop (con 1 slot) gan nhu dong thoi — ca 2 cung doc room voi slot.available = 1, ca 2 cung qua dieu kien kiem tra, ca 2 cung tru available xuong 0 va luu — ca 2 deu duoc xac nhan dat phong thanh cong cho cung 1 slot, dan den xung dot lich hop that su khi den gio.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch4, dua tren mo ta counter_no_atomic)", "url": "", "pattern_ids": ["counter_no_atomic"]},

    # ============= CALLBACK_HELL (15 doc) =============
    {"id": "js-b4-ch-001", "title": "Callback Hell: Xu Ly Dang Ky Tai Khoan Voi 4 Buoc Callback Long Nhau (Validate, Tao User, Gui Email, Log)",
     "content": "function register(data, cb) { validateInput(data, function(err) { if (err) return cb(err); createUser(data, function(err, user) { if (err) return cb(err); sendWelcomeEmail(user, function(err) { if (err) return cb(err); logRegistration(user, function(err) { cb(err, user) }) }) }) }) } — 4 cap callback long nhau, moi cap phai tu xu ly error rieng, code thut le sau 4 cap kho doc — de sot 1 nhanh return trong bat ky cap nao deu gay double-callback, va them 1 buoc moi (vi du 'kiem tra captcha') doi hoi them 1 cap long nua, code ngay cang kho bao tri.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-002", "title": "Callback Hell: Xu Ly Thanh Toan Voi Callback Long Kiem Tra So Du, Tru Tien, Ghi Log, Gui Thong Bao",
     "content": "function processPayment(userId, amount, cb) { getBalance(userId, function(err, balance) { if (balance < amount) return cb(new Error('insufficient funds')); deductBalance(userId, amount, function(err) { logTransaction(userId, amount, function(err) { notifyUser(userId, function(err) { cb(null, 'success') }) }) }) }) } — 4 cap callback long nhau trong luong thanh toan quan trong — nhieu cap giua khong kiem tra err truoc khi tiep tuc (deductBalance, logTransaction), nghia la neu 1 buoc that bai giua chung, luong van tiep tuc chay cac buoc sau nhu khong co gi xay ra, co the ghi log giao dich thanh cong du tien chua thuc su duoc tru.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-003", "title": "Callback Hell: Doc Va Xu Ly Chuoi 3 File Cau Hinh Phu Thuoc Lan Nhau Bang fs.readFile Callback",
     "content": "fs.readFile('base.json', 'utf8', function(err, base) { const baseConfig = JSON.parse(base); fs.readFile(baseConfig.envFile, 'utf8', function(err, env) { const envConfig = JSON.parse(env); fs.readFile(envConfig.secretsFile, 'utf8', function(err, secrets) { const finalConfig = merge(baseConfig, envConfig, JSON.parse(secrets)); startApp(finalConfig) }) }) }) — moi lan doc file phu thuoc noi dung file truoc do (ten file can doc tiep theo nam trong file vua doc), tao chuoi callback long 3 cap khong the flatten don gian bang Promise.all vi that su tuan tu — nhung van nen dung async/await de code de doc hon, callback hien tai khong co xu ly loi cho tung buoc doc file.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-004", "title": "Callback Hell: Luong Xu Ly Upload Anh Voi Resize, Watermark, Upload S3, Cap Nhat Database Long Nhau",
     "content": "function processImage(filePath, cb) { resizeImage(filePath, function(err, resized) { addWatermark(resized, function(err, watermarked) { uploadToS3(watermarked, function(err, url) { updateDatabase(url, function(err) { cleanupTempFiles(filePath, function(err) { cb(null, url) }) }) }) }) }) } — 5 cap callback long nhau trong pipeline xu ly anh — them 1 buoc moi (vi du 'nen anh truoc khi resize') doi hoi chen vao giua chuoi long nay, de gay loi khi sua vi phai dieu chinh dung cap thut le, kho debug khi loi xay ra o cap giua ma stack trace khong ro rang cap nao that bai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-005", "title": "Callback Hell: Xac Thuc OAuth Voi Chuoi Callback Lay Token, Lay User Info, Tao Session",
     "content": "function oauthLogin(code, cb) { exchangeCodeForToken(code, function(err, token) { getUserInfoFromProvider(token, function(err, userInfo) { findOrCreateUser(userInfo, function(err, user) { createSession(user, function(err, session) { cb(null, session) }) }) }) }) } — 4 cap callback trong luong dang nhap OAuth — moi cap chi kiem tra err rieng le ma khong co diem tap trung xu ly loi chung, khien code goi ham phai xu ly loi khac nhau tuy vao no xay ra o buoc nao, gay kho khan khi hien thi thong bao loi nhat quan cho user.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-006", "title": "Callback Hell: Xu Ly Don Hang E-commerce Voi Kiem Tra Ton Kho, Tru Kho, Tao Don, Gui Email Xac Nhan",
     "content": "function createOrder(cartItems, cb) { checkInventory(cartItems, function(err, available) { if (!available) return cb(new Error('out of stock')); deductInventory(cartItems, function(err) { createOrderRecord(cartItems, function(err, order) { chargePayment(order, function(err) { sendOrderConfirmation(order, function(err) { cb(null, order) }) }) }) }) }) } — 5 cap callback long nhau cho luong tao don hang quan trong nhat cua he thong — neu chargePayment() that bai SAU KHI deductInventory() da chay, khong co logic rollback (hoan lai kho hang) trong chuoi callback nay, gay mat dong bo giua ton kho thuc te va don hang chua duoc thanh toan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-007", "title": "Callback Hell: Chuoi Xu Ly Video Upload Voi Transcode, Tao Thumbnail, Upload CDN, Index Search",
     "content": "function processVideo(videoPath, cb) { transcodeVideo(videoPath, function(err, transcoded) { generateThumbnail(transcoded, function(err, thumb) { uploadToCDN(transcoded, thumb, function(err, urls) { indexForSearch(urls, function(err) { notifyUploadComplete(urls, function(err) { cb(null, urls) }) }) }) }) }) } — 5 cap callback long trong pipeline video, moi buoc co the mat vai giay den vai phut (transcode video lon) — khong co co che theo doi tien do (progress) giua cac buoc, user chi thay 'dang xu ly' ma khong biet dang o buoc nao trong 5 buoc, trai nghiem rat te cho video lon.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-008", "title": "Callback Hell: Luong Khoi Tao Server Voi Ket Noi Database, Redis, Load Config, Dang Ky Route Long Nhau",
     "content": "function startServer(cb) { connectDatabase(function(err) { connectRedis(function(err) { loadRemoteConfig(function(err, config) { registerRoutes(config, function(err) { listenOnPort(config.port, function(err) { cb(null, 'Server started') }) }) }) }) }) } — 5 cap callback long trong quy trinh khoi dong server — 3 buoc dau (database, Redis, config) hoan toan doc lap va co the chay song song, nhung callback hell buoc phai viet tuan tu, lam thoi gian khoi dong server lau hon can thiet ngoai van de code kho doc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-009", "title": "Callback Hell: Xu Ly Import Du Lieu CSV Voi Parse, Validate Tung Dong, Insert Database, Bao Cao Ket Qua",
     "content": "function importCsv(filePath, cb) { parseCSVFile(filePath, function(err, rows) { validateAllRows(rows, function(err, validRows, invalidRows) { insertRowsToDb(validRows, function(err, insertedCount) { generateImportReport(insertedCount, invalidRows.length, function(err, report) { sendReportEmail(report, function(err) { cb(null, report) }) }) }) }) }) } — 5 cap callback long trong luong import du lieu — validateAllRows() xu ly TAT CA dong truoc khi insertRowsToDb() bat dau, nghia la voi file lon (hang trieu dong) toan bo du lieu phai duoc giu trong memory cung 1 luc thay vi xu ly theo stream, gay nguy co het bo nho voi file du lieu qua lon.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-010", "title": "Callback Hell: Luong Reset Mat Khau Voi Xac Thuc Token, Cap Nhat Password, Vo Hieu Session Cu, Gui Email",
     "content": "function resetPassword(token, newPassword, cb) { verifyResetToken(token, function(err, userId) { if (err) return cb(err); hashPassword(newPassword, function(err, hash) { updateUserPassword(userId, hash, function(err) { invalidateAllSessions(userId, function(err) { sendPasswordChangedEmail(userId, function(err) { cb(null, 'success') }) }) }) }) }) } — 5 cap callback long trong luong bao mat quan trong — chi buoc dau tien (verifyResetToken) co check 'if (err) return cb(err)', cac buoc con lai khong kiem tra err truoc khi tiep tuc, nghia la neu hashPassword() that bai, code van tiep tuc goi updateUserPassword() voi hash undefined, co nguy co luu password rong/sai vao database.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-011", "title": "Callback Hell: Xu Ly Webhook Nhan Tu Payment Provider Voi Verify Signature, Parse Event, Cap Nhat Don Hang, Log",
     "content": "function handleStripeWebhook(req, cb) { verifySignature(req, function(err) { if (err) return cb(err); parseWebhookEvent(req.body, function(err, event) { findOrderByPaymentId(event.paymentId, function(err, order) { updateOrderStatus(order, event.status, function(err) { logWebhookEvent(event, function(err) { cb(null, 'processed') }) }) }) }) }) } — 5 cap callback long trong xu ly webhook thanh toan — day la endpoint hay bi payment provider retry nhieu lan neu response cham (do do sau qua nhieu cap callback), lam tang nguy co xu ly trung lap 1 webhook event nhieu lan neu response bi timeout truoc khi chuoi callback kip hoan tat.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-012", "title": "Callback Hell: Luong Xu Ly Chat Message Voi Kiem Duyet Noi Dung, Luu Database, Broadcast, Ghi Analytics",
     "content": "function handleChatMessage(msg, cb) { moderateContent(msg.text, function(err, isClean) { if (!isClean) return cb(new Error('flagged content')); saveMessageToDb(msg, function(err, saved) { broadcastToRoom(msg.roomId, saved, function(err) { trackAnalytics(msg, function(err) { cb(null, saved) }) }) }) }) } — 4 cap callback long trong luong chat realtime — do do sau nhieu cap, do tre tu luc user gui tin nhan den luc tin nhan hien thi cho nguoi khac (broadcastToRoom, cap thu 3) bi keo dai boi ca thoi gian moderateContent() va saveMessageToDb() chay truoc no, du 2 buoc dau khong lien quan truc tiep den viec hien thi tin nhan ngay lap tuc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-013", "title": "Callback Hell: Xu Ly Xoa Tai Khoan Nguoi Dung Voi Xoa Du Lieu Lien Quan O Nhieu Bang Long Nhau",
     "content": "function deleteAccount(userId, cb) { deleteUserPosts(userId, function(err) { deleteUserComments(userId, function(err) { deleteUserFiles(userId, function(err) { deleteUserSessions(userId, function(err) { deleteUserRecord(userId, function(err) { cb(null, 'deleted') }) }) }) }) }) } — 5 cap callback xoa du lieu tuan tu qua nhieu bang — cac thao tac xoa nay HOAN TOAN doc lap nhau (khong co foreign key rang buoc thu tu xoa trong vi du nay), nen viet tuan tu vua kho doc vua cham hon can thiet, dong thoi neu 1 buoc giua chung that bai (vi du deleteUserFiles loi do quyen S3), du lieu bi xoa mot phan (orphan data) ma khong co rollback.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-014", "title": "Callback Hell: Luong Xu Ly Tim Kiem Voi Query Elasticsearch, Enrich Ket Qua Tu Database, Cache Ket Qua",
     "content": "function search(query, cb) { queryElasticsearch(query, function(err, hits) { enrichWithDbData(hits, function(err, enriched) { applyPersonalization(enriched, function(err, personalized) { cacheSearchResult(query, personalized, function(err) { cb(null, personalized) }) }) }) }) } — 4 cap callback trong luong tim kiem — endpoint search thuong can phan hoi rat nhanh (duoi 200ms de UX tot), nhung callback hell buoc phai cho tung buoc hoan tat tuan tu bao gom ca cacheSearchResult() (chi de luu cache cho lan sau, khong can thiet cho response hien tai) truoc khi tra ket qua ve, lam cham response mot cach khong can thiet.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
    {"id": "js-b4-ch-015", "title": "Callback Hell: Xu Ly Migration Du Lieu Legacy Voi Doc File Cu, Transform Format, Validate, Ghi Vao He Thong Moi",
     "content": "function migrateLegacyData(filePath, cb) { readLegacyFile(filePath, function(err, rawData) { transformToNewFormat(rawData, function(err, transformed) { validateAgainstNewSchema(transformed, function(err, valid) { if (!valid) return cb(new Error('validation failed')); writeToNewSystem(transformed, function(err) { generateMigrationLog(transformed, function(err) { cb(null, 'migrated') }) }) }) }) }) } — 5 cap callback long trong script migration mot lan — do khong dung async/await, moi khi debug loi migration that bai giua chung, phai them console.log() thu cong o tung cap va chay lai toan bo script tu dau (khong the dat breakpoint ro rang theo tung buoc nhu voi cu phap tuan tu cua await).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch4, dua tren mo ta callback_hell)", "url": "", "pattern_ids": ["callback_hell"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
