"""
AI2 — batch 2 mo rong KB: viet tay 15 doc/pattern cho 3 pattern mong nhat con
lai sau batch 1 (buffer_leak:2, concurrent_write_array:2, context_loss_this:2).
Moi doc la 1 tinh huong code CU THE khac nhau that su (ten ham, thu vien, boi
canh khac nhau), khong dung khuon cau lap lai.

Muc tieu thuc te: ~45 doc batch nay (tiep noi batch1, huong toi ~400-500 doc
tong the — xem RESEARCH_LOG ghi chu tradeoff quy mo vs chat luong).

Chay: python add_batch2_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ============= BUFFER_LEAK (15 doc) =============
    {"id": "js-b2-bl-001", "title": "Buffer Leak: HTTP Response Stream Khong Duoc Destroy Khi Client Huy Request Giua Chung",
     "content": "app.get('/download/:file', (req, res) => { const rs = fs.createReadStream(getPath(req.params.file)); rs.pipe(res) }) — neu client dong tab/huy request truoc khi download xong, res bi dong dot ngot nhung rs (ReadStream) khong tu dong destroy vi dung .pipe() truc tiep thay vi stream.pipeline(). Duoi tai lon nhieu client huy download giua chung se tich luy hang tram ReadStream con mo, giu file descriptor va buffer memory khong duoc giai phong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-002", "title": "Buffer Leak: Database Cursor Stream Khong Close Khi Vong Lap Break Som",
     "content": "const cursor = db.collection('logs').find().stream(); for await (const doc of cursor) { if (doc.level === 'error') break; process(doc) } — vong lap 'break' som khi tim thay dieu kien mong muon, nhung cursor stream khong duoc goi cursor.close() sau do — MongoDB driver van giu ket noi cursor mo o server side cho den khi timeout tu nhien (thuong 10 phut), neu ham nay duoc goi thuong xuyen se tich luy nhieu cursor mo dong thoi tren server database.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-003", "title": "Buffer Leak: WebSocket Binary Message Buffer Khong Duoc Giai Phong Khi Parse Loi",
     "content": "socket.on('message', (data) => { const buf = Buffer.from(data); const parsed = customBinaryParser.parse(buf); handleMessage(parsed) }) — neu customBinaryParser.parse() throw loi (du lieu binary bi hong), buf khong duoc giai phong tham chieu ro rang va co the bi giu lai trong closure cua error handler neu code catch loi va log ca buf de debug — lam Buffer lon (payload binary co the vai MB) ton dong trong memory, tich luy qua nhieu message loi gay memory leak dan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-004", "title": "Buffer Leak: Child Process Stdout Stream Khong Duoc Unpipe Sau Khi Process Ket Thuc",
     "content": "const child = spawn('ffmpeg', args); child.stdout.pipe(outputStream); child.on('exit', () => { console.log('done') }) — khi child process thoat, stdout stream cua no khong tu dong duoc unpipe/destroy khoi outputStream, đe lai 1 tham chieu 'mo cho' trong outputStream — neu ham nay duoc goi lien tuc (vi du xu ly video hang loat), moi lan goi de lai 1 stream object 'mo' chua duoc GC, dan den memory tang dan theo thoi gian chay.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-005", "title": "Buffer Leak: Multer Upload Temp File Khong Xoa Khi Validation Sau Do That Bai",
     "content": "app.post('/upload', upload.single('file'), async (req, res) => { const isValid = await validateContent(req.file.path); if (!isValid) return res.status(400).send('invalid'); await processFile(req.file.path) }) — nhanh validation that bai return ngay ma khong xoa file tam ma multer da luu vao disk (req.file.path) — moi request upload file khong hop le de lai 1 file rac trong thu muc tmp, qua thoi gian tich luy chiem het dung luong disk neu khong co cron cleanup rieng.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-006", "title": "Buffer Leak: gRPC Stream Khong Duoc Cancel Khi Client Timeout Phia Ung Dung",
     "content": "async function callWithTimeout(client, request, ms) { return Promise.race([client.streamCall(request), new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), ms))]) } — khi Promise.race tra ve do timeout thang, client.streamCall() van dang chay ngam va gRPC stream van mo o phia server — khong co call.cancel() duoc goi cho nhanh thua cuoc, tich luy nhieu request timeout se de lai nhieu gRPC stream mo tren ca client va server.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-007", "title": "Buffer Leak: Log Rotation Stream Cu Khong Duoc End Khi Chuyen File Log Moi",
     "content": "function rotateLog() { const newStream = fs.createWriteStream(getNewLogPath()); currentLogStream = newStream } — khi rotate sang file log moi, WriteStream cu (currentLogStream truoc do) bi ghi de bien tham chieu ma khong goi .end() truoc — cac du lieu con dang buffer trong stream cu co the bi mat (chua flush xong xuong disk) va bo nho cua stream cu khong duoc giai phong dung cach, moi lan rotate (thuong hang ngay) de lai 1 WriteStream 'mo cho' trong memory.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-008", "title": "Buffer Leak: Redis Subscribe Client Khong Unsubscribe Khi Component React Unmount",
     "content": "useEffect(() => { const sub = redisSubClient.subscribe('channel'); sub.on('message', handleMessage); return undefined }, []) — cleanup function cua useEffect tra ve undefined thay vi 1 ham goi sub.unsubscribe(), nen khi component unmount (user chuyen trang), subscription Redis van con hoat dong o phia client, tiep tuc nhan message va giu buffer trong memory browser cho 1 component da khong con ton tai tren man hinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-009", "title": "Buffer Leak: Zip Archive Stream Khong Destroy Khi Nen That Bai Giua Chung",
     "content": "function createZipResponse(files, res) { const archive = archiver('zip'); archive.pipe(res); files.forEach(f => archive.file(f.path, { name: f.name })); archive.finalize() } — neu 1 file trong danh sach bi loi doc (file da bi xoa giua luc dang nen), archive emit event 'error' nhung khong co handler bat loi nay de goi archive.abort()/destroy() — archive stream tiep tuc ton tai o trang thai treo, giu tham chieu toi cac ReadStream con lai chua duoc dong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-010", "title": "Buffer Leak: Video Transcoding Pipe Khong Cleanup Khi User Huy Job Giua Chung",
     "content": "function transcodeVideo(inputPath, jobId) { const ff = ffmpeg(inputPath); activeJobs.set(jobId, ff); ff.on('end', () => activeJobs.delete(jobId)); ff.run() } function cancelJob(jobId) { activeJobs.delete(jobId) } — ham cancelJob() chi xoa entry khoi Map activeJobs nhung khong goi ff.kill() de dung thuc su tien trinh ffmpeg dang chay — process con (child process) va cac stream cua no van tiep tuc chay ngam, tieu ton CPU/memory ma khong ai theo doi duoc nua vi da bi xoa khoi activeJobs.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-011", "title": "Buffer Leak: SSE Connection Khong Duoc Cleanup Khi Client Mat Ket Noi Dot Ngot",
     "content": "app.get('/events', (req, res) => { res.setHeader('Content-Type', 'text/event-stream'); const listener = data => res.write(`data: ${data}\\n\\n`); eventBus.on('update', listener) }) — khong co req.on('close', () => eventBus.off('update', listener)) — khi client mat mang dot ngot (khong dong ket noi 'sach'), listener van con dang ky tren eventBus va tiep tuc goi res.write() tren 1 response da chet, moi client mat ket noi de lai 1 listener 'ma' tich luy dan trong eventBus.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-012", "title": "Buffer Leak: CSV Parser Stream Khong Destroy Khi Dong Bo Loi Format Phat Hien Som",
     "content": "function parseCsvStrict(filePath) { return new Promise((resolve, reject) => { const stream = fs.createReadStream(filePath).pipe(csvParser()); stream.on('data', row => { if (!isValidRow(row)) reject(new Error('bad row')) }); stream.on('end', () => resolve()) }) } — nhanh reject() khi gap row loi khong goi stream.destroy() truoc — ReadStream goc van tiep tuc doc phan con lai cua file tu disk du Promise da reject, lang phi I/O va giu stream mo lau hon can thiet cho toi khi doc het file that su.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-013", "title": "Buffer Leak: Puppeteer Browser Page Khong Duoc Close Khi Screenshot That Bai",
     "content": "async function captureScreenshot(url) { const page = await browser.newPage(); await page.goto(url); const buf = await page.screenshot(); return buf } — neu page.goto(url) throw loi (trang timeout hoac loi mang), khong co try/finally de goi page.close() — moi lan goi that bai de lai 1 page (tab) mo trong Puppeteer browser instance, chay lien tuc voi nhieu URL loi se tich luy hang chuc tab an ngam, moi tab chiem vai chuc MB RAM cho browser process.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-014", "title": "Buffer Leak: Kafka Consumer Stream Khong Duoc Disconnect Khi App Restart Nong (Hot Reload)",
     "content": "const consumer = kafka.consumer({ groupId: 'my-group' }); await consumer.connect(); await consumer.run({ eachMessage: handleMessage }) — trong moi truong dev dung nodemon/hot-reload, moi lan file thay doi va module duoc load lai, code nay chay lai tu dau va tao 1 consumer MOI ma khong disconnect() consumer cu — sau vai lan hot-reload, co nhieu consumer cung group id dang chay song song, moi consumer giu ket noi TCP rieng toi Kafka broker.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b2-bl-015", "title": "Buffer Leak: Ham Nen Response Gzip Khong Destroy Stream Khi Client Abort Giua Chung",
     "content": "app.get('/api/export', (req, res) => { const gzip = zlib.createGzip(); res.setHeader('Content-Encoding', 'gzip'); dataStream.pipe(gzip).pipe(res) }) — neu client abort request giua luc dang nen/gui du lieu, res dong dot ngot nhung .pipe() truc tiep (khong dung pipeline()) khien gzip transform stream va dataStream nguon khong duoc destroy dung cach — cac buffer noi bo cua zlib (compression state) va data con dang doc tu nguon van ton tai trong memory cho toi khi GC don dep, co the mat vai giay/phut duoi tai cao.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},

    # ============= CONCURRENT_WRITE_ARRAY (15 doc) =============
    {"id": "js-b2-cwa-001", "title": "Concurrent Write: Nhieu Webhook Handler Cung Push Vao Mang Log Chung Trong Memory",
     "content": "let recentEvents = []; app.post('/webhook', (req, res) => { recentEvents.push(req.body); if (recentEvents.length > 100) recentEvents.shift(); res.sendStatus(200) }) — nhieu webhook toi dong thoi (vi du tu Stripe gui hang loat event lien tiep) cung push/shift vao mang recentEvents khong dong bo — do Node.js don luong nen tung dong lenh khong bi ngat quang, NHUNG neu handler duoc lam async (them await truoc do), race condition thuc su xuat hien: 2 request xen ke co the doc do dai mang truoc khi ben kia push xong, dan den shift() xoa nham item vua duoc them.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-002", "title": "Concurrent Write: Nhieu Worker Thread Cung Ghi Ket Qua Vao Mang Shared Qua postMessage Khong Dong Bo",
     "content": "const results = []; workers.forEach(w => w.on('message', (data) => { results.push(data); if (results.length === workers.length) onAllDone(results) })) — cac worker thread hoan thanh cong viec o thoi diem khac nhau va goi postMessage doc lap — neu 2 worker hoan thanh gan nhu cung luc, ca 2 'message' handler co the doc results.length TRUOC khi ben kia kip push, khien dieu kien 'results.length === workers.length' khong bao gio dung du tat ca worker da that su xong, onAllDone() khong bao gio duoc goi (hang vo han).",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-003", "title": "Concurrent Write: Nhieu Request API Cung Ghi Vao Mang Cart Items Trong Session Object",
     "content": "app.post('/cart/add', async (req, res) => { const session = await getSession(req.sessionId); session.items.push(req.body.item); await saveSession(session); res.json(session) }) — 2 request 'them vao gio hang' gan nhu dong thoi tu cung 1 user (vi du double-click nut them hang) cung goi getSession() doc cung 1 ban sao session cu, moi request push item vao ban sao rieng cua no, roi ca 2 goi saveSession() — request luu sau se ghi de hoan toan session cua request luu truoc, item cua request truoc bi mat vinh vien.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-004", "title": "Concurrent Write: Batch Job Va API Request Cung Ghi Vao Mang Inventory Reservation",
     "content": "let reservations = []; function reserveStock(productId, qty) { const current = reservations.filter(r => r.productId === productId).reduce((s, r) => s + r.qty, 0); if (current + qty <= stock[productId]) { reservations.push({ productId, qty }); return true } return false } — ham nay duoc goi dong thoi tu nhieu request API va 1 cron job dinh ky kiem tra reservation het han — thao tac doc (filter+reduce de tinh current) va ghi (push) khong atomic, 2 request gan nhu dong thoi co the cung tinh ra current giong nhau va ca 2 cung push, dan den tong so luong reserve vuot qua stock thuc te (oversell).",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-005", "title": "Concurrent Write: Multiple SSE Client Connect Cung Luc Ghi Vao Mang Danh Sach Client Cua 1 Room",
     "content": "const roomClients = {}; function joinRoom(roomId, clientRes) { if (!roomClients[roomId]) roomClients[roomId] = []; roomClients[roomId].push(clientRes) } — neu 2 client cung join 1 room MOI (chua ton tai truoc do) gan nhu dong thoi trong 1 ham async wrapper ben ngoai co await truoc doan nay, ca 2 co the cung thay roomClients[roomId] la undefined va cung khoi tao mang moi — mang cua nguoi join truoc bi ghi de, client do bi 'mat tich' khoi danh sach nhan broadcast cua room.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-006", "title": "Concurrent Write: GraphQL Subscription Resolver Ghi Vao Mang Pending Notifications Chung",
     "content": "let pendingNotifications = new Map(); function queueNotification(userId, notif) { const list = pendingNotifications.get(userId) || []; list.push(notif); pendingNotifications.set(userId, list) } — nhieu subscription event (order_updated, comment_added...) cho cung 1 userId co the trigger queueNotification() gan nhu dong thoi qua cac resolver khac nhau — moi lan doc list cu qua get() truoc khi push co the doc phai ban 'chua co notification moi nhat tu resolver khac vua ghi', dan den 1 trong cac notification bi ghi de mat khi set() lai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-007", "title": "Concurrent Write: Test Runner Song Song Cung Ghi Ket Qua Vao Mang Report Chung",
     "content": "let testResults = []; async function runTest(testCase) { const result = await execute(testCase); testResults.push(result) } await Promise.all(testCases.map(runTest)) — Promise.all() chay tat ca runTest() song song, moi test co thoi gian hoan tat khac nhau — ban than push() tren array trong Node.js la an toan (khong bi mat data vi don luong), NHUNG neu logic sau do dung testResults.length de gan index cho report (vi du testResults[testResults.length] = extra), race giua doc length va ghi co the ghi de item.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-008", "title": "Concurrent Write: Chat App Nhieu Tab Cung Ghi Vao localStorage Array Tin Nhan Chua Gui",
     "content": "function queueOfflineMessage(msg) { const queue = JSON.parse(localStorage.getItem('pendingMsgs') || '[]'); queue.push(msg); localStorage.setItem('pendingMsgs', JSON.stringify(queue)) } — user mo 2 tab trinh duyet cung app, ca 2 tab cung goi ham nay khi mat mang gan nhu dong thoi — moi tab doc localStorage rieng (JSON.parse) truoc khi tab kia kip setItem(), tab ghi sau se ghi de toan bo mang, tin nhan cua tab ghi truoc bi mat khoi hang doi gui lai khi co mang tro lai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-009", "title": "Concurrent Write: Health Check Nhieu Instance Cung Ghi Vao Mang Trang Thai Cluster Trong Redis",
     "content": "async function reportHealthy(instanceId) { const list = JSON.parse(await redis.get('healthy_instances') || '[]'); if (!list.includes(instanceId)) list.push(instanceId); await redis.set('healthy_instances', JSON.stringify(list)) } — nhieu instance cua cung 1 service goi ham nay gan nhu dong thoi khi khoi dong (deploy cung luc N pod) — moi instance doc gia tri Redis truoc khi cac instance khac kip ghi, dan den chi 1-2 instance duoc luu vao danh sach cuoi cung thay vi tat ca N instance, do cac lan ghi ghi de len nhau (last-write-wins).",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-010", "title": "Concurrent Write: Multiple File Watcher Callback Cung Ghi Vao Mang Changed Files Buffer",
     "content": "let changedFiles = []; let flushTimer = null; watcher.on('change', (path) => { changedFiles.push(path); if (!flushTimer) flushTimer = setTimeout(() => { processFiles(changedFiles); changedFiles = []; flushTimer = null }, 500) }) — neu setTimeout callback dang chay (dang trong processFiles) va 1 event 'change' moi toi dung luc do, doan code kiem tra '!flushTimer' co the khong con chinh xac tuy timing, gay tinh huong file moi bi push vao mang VUA duoc gan lai '= []' o dong ke tiep, mat item vua push.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-011", "title": "Concurrent Write: Leaderboard Update Nhieu Player Cung Ghi Vao Mang Top10 Trong Memory Cache",
     "content": "let top10Cache = []; function updateScore(playerId, score) { top10Cache = top10Cache.filter(p => p.id !== playerId); top10Cache.push({ id: playerId, score }); top10Cache.sort((a,b) => b.score - a.score).slice(0, 10) } — nhieu nguoi choi ghi diem gan nhu dong thoi (async wrapper ben ngoai co await database write truoc doan nay) — 2 lan goi doc top10Cache cu truoc khi ben kia kip gan lai bien, dan den 1 trong 2 update bi mat hoan toan khoi cache (ghi de bang phien ban cu hon), leaderboard hien sai diem cho toi lan update tiep theo.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-012", "title": "Concurrent Write: Nhieu HTTP Retry Task Cung Ghi Vao Mang Failed Requests De Bao Cao",
     "content": "const failedRequests = []; async function fetchWithLog(url) { try { return await fetch(url) } catch (e) { failedRequests.push({ url, error: e.message, time: Date.now() }); throw e } } await Promise.allSettled(urls.map(fetchWithLog)) — nhieu request that bai gan nhu dong thoi cung push vao failedRequests — vi Node.js don luong nen push() rieng le an toan, nhung neu code sau do doc failedRequests.length ngay lap tuc (khong doi Promise.allSettled xong het) de quyet dinh co retry hay khong, co the doc duoc gia tri chua day du do cac Promise khac van dang chay.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-013", "title": "Concurrent Write: Rate Limiter Sliding Window Ghi Vao Mang Timestamp Request Khong Atomic",
     "content": "const requestLog = new Map(); function checkRateLimit(userId) { const now = Date.now(); const timestamps = requestLog.get(userId) || []; const recent = timestamps.filter(t => now - t < 60000); recent.push(now); requestLog.set(userId, recent); return recent.length <= 100 } — trong middleware async (co await truoc doan check nay, vi du await verifyUser()), 2 request gan nhu dong thoi tu cung user cung doc timestamps cu, ca 2 cung filter+push roi set() — 1 trong 2 lan ghi bi mat, khien rate limit dem thieu request thuc te, cho phep vuot qua gioi han da dat ra.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-014", "title": "Concurrent Write: Distributed Lock Retry Nhieu Instance Cung Ghi Vao Mang Waiting Queue Local",
     "content": "let waitingQueue = []; async function acquireLockWithQueue(key) { waitingQueue.push(key); await tryAcquire(key); waitingQueue = waitingQueue.filter(k => k !== key) } — nhieu request cung goi acquireLockWithQueue() gan nhu dong thoi — thao tac filter (xoa key khoi hang doi) cua 1 request co the chay xen ke voi push() cua request khac dang bat dau, neu 2 key giong nhau (cung 1 resource duoc lock nhieu lan), filter co the xoa nham ca 2 entry thay vi chi entry vua hoan tat.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b2-cwa-015", "title": "Concurrent Write: Nhieu API Consumer Cung Ghi Vao Mang Audit Trail Trong 1 Object Response Chia Se",
     "content": "function createAuditableResponse() { const audit = { steps: [] }; return { audit, logStep: (name) => audit.steps.push({ name, time: Date.now() }) } } const shared = createAuditableResponse(); await Promise.all([taskA(shared.logStep), taskB(shared.logStep), taskC(shared.logStep)]) — 3 task chay song song cung goi logStep() ghi vao cung 1 mang audit.steps qua closure shared — ban than push khong bi mat du lieu (JS don luong), nhung NEU code khac dong thoi doc audit.steps.length de gioi han so buoc hien thi (vi du chi hien 5 buoc dau), thu tu cac buoc ghi vao co the khong phan anh dung thu tu logic thuc te cua 3 task, gay audit trail sai lech thu tu.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch2, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},

    # ============= CONTEXT_LOSS_THIS (15 doc) =============
    {"id": "js-b2-clt-001", "title": "Context Loss: Array.prototype.map Voi Method Reference Truc Tiep Lam Mat 'this' Cua Class",
     "content": "class UserFormatter { constructor(prefix) { this.prefix = prefix } format(user) { return this.prefix + user.name } } const formatter = new UserFormatter('Mr. '); const names = users.map(formatter.format) — truyen formatter.format truc tiep vao map() tach method khoi instance goc, ben trong format() 'this' khong con tro ve formatter (undefined trong strict mode), truy cap this.prefix nem TypeError 'Cannot read property prefix of undefined' cho MOI phan tu trong mang.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-002", "title": "Context Loss: Destructuring Method Ra Khoi Object Config Truoc Khi Goi",
     "content": "const dbClient = { conn: null, query(sql) { return this.conn.execute(sql) } }; const { query } = dbClient; await query('SELECT 1') — destructuring 'query' ra khoi dbClient tach ham khoi object goc, khi goi query() truc tiep, 'this' ben trong khong con la dbClient (undefined), this.conn nem TypeError — loi rat de mac phai khi code refactor tu 'dbClient.query()' sang import ham rieng le de 'gon code hon'.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-003", "title": "Context Loss: Vue Component Method Truyen Lam Callback Cho Thu Vien Third-Party",
     "content": "export default { methods: { onUploadComplete(result) { this.uploadedFiles.push(result) } }, mounted() { uploaderLib.init({ onComplete: this.onUploadComplete }) } } — truyen this.onUploadComplete truc tiep vao config cua thu vien ngoai lam mat lien ket voi component instance khi thu vien do goi callback nay — this.uploadedFiles ben trong nem loi undefined vi 'this' luc callback thuc thi khong con la component Vue nua, ma la context ma thu vien uploaderLib goi callback tu do (thuong la undefined hoac object cua thu vien).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-004", "title": "Context Loss: Array.prototype.sort Voi Comparator Method Cua Class Truy Cap Field Instance",
     "content": "class PriorityQueue { constructor(weights) { this.weights = weights } compareFn(a, b) { return this.weights[a] - this.weights[b] } sortItems(items) { return items.sort(this.compareFn) } } — sortItems() truyen this.compareFn vao sort() nhung khong bind — Array.prototype.sort goi comparator nhu 1 function doc lap, ben trong compareFn 'this' khong con tro ve instance PriorityQueue, this.weights la undefined, gay TypeError ngay trong lan so sanh dau tien khi sort() bat dau chay.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-005", "title": "Context Loss: Express Router Class-Based Controller Dang Ky Method Truc Tiep Lam Route Handler",
     "content": "class UserController { constructor(db) { this.db = db } async getUser(req, res) { const user = await this.db.findUser(req.params.id); res.json(user) } } const controller = new UserController(db); router.get('/users/:id', controller.getUser) — Express goi controller.getUser truc tiep nhu 1 function doc lap khi co request toi, 'this' ben trong khong con la controller instance, this.db la undefined, request nem TypeError thay vi tra ve du lieu user.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-006", "title": "Context Loss: setInterval Trong Constructor Goi Method Instance Ma Khong Bind O Non-Class-Field Style",
     "content": "class HeartbeatMonitor { constructor(socket) { this.socket = socket; this.missedCount = 0; setInterval(this.checkHeartbeat, 5000) } checkHeartbeat() { this.missedCount++; if (this.missedCount > 3) this.socket.disconnect() } } — checkHeartbeat duoc khai bao la method thuong (khong phai class field arrow function) va truyen truc tiep vao setInterval — moi lan interval chay, 'this' khong con la instance HeartbeatMonitor, this.missedCount++ tao ra 1 property moi tren global object (hoac undefined error o strict mode) thay vi tang dung bien cua instance.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-007", "title": "Context Loss: React Class Component Event Handler Khong Bind Trong Constructor",
     "content": "class SearchBox extends React.Component { constructor(props) { super(props); this.state = { query: '' } } handleChange(e) { this.setState({ query: e.target.value }) } render() { return <input onChange={this.handleChange} /> } } — handleChange duoc truyen truc tiep vao onChange ma khong bind(this) trong constructor hoac dung class field arrow function — khi user go vao input, this.setState nem TypeError vi 'this' ben trong handleChange la undefined thay vi component instance, component khong bao gio cap nhat duoc state.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-008", "title": "Context Loss: Object.entries().forEach Voi Method Object Lam Callback Truc Tiep",
     "content": "const validator = { errors: [], validate(key, val) { if (!val) this.errors.push(key) } }; Object.entries(formData).forEach(([key, val]) => validator.validate(key, val)) — cach nay THUC RA dung (vi dung arrow function wrap), nhung neu code duoc 'toi uu' thanh Object.entries(formData).forEach(validator.validate) (bo arrow function di cho 'ngan gon'), 'this' ben trong validate() se mat, this.errors.push() nem TypeError — day la loi thuong gap khi refactor code tuong nham la tuong duong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-009", "title": "Context Loss: Passport.js Custom Strategy Verify Callback Mat This Cua Strategy Instance",
     "content": "class CustomStrategy extends passport.Strategy { constructor(options) { super(); this.options = options } authenticate(req) { verifyToken(req.headers.token, this.success) } success(user) { this.pass(user) } } — truyen this.success lam callback cho verifyToken() ma khong bind — khi verifyToken() goi callback thanh cong, 'this' ben trong success() khong con la CustomStrategy instance, this.pass() (method ke thua tu passport.Strategy) khong ton tai tren context sai do, gay loi xac thuc that bai am tham khong ro nguyen nhan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-010", "title": "Context Loss: Testing Library (Jest) Mock Implementation Goi Method That Thay Vi Mock Do Mat This",
     "content": "class ApiClient { constructor(baseUrl) { this.baseUrl = baseUrl } get(path) { return fetch(this.baseUrl + path) } } jest.spyOn(ApiClient.prototype, 'get').mockImplementation(function() { return this.baseUrl }) — mockImplementation dung 'function' thuong (dung), NHUNG neu code test lai truyen mock nhu arrow function (() => this.baseUrl) thay vi function thuong, 'this' se khong con duoc bind dong theo instance goi, mock luon tra ve undefined bat ke instance nao goi get(), lam sai lech ket qua test.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-011", "title": "Context Loss: Chart.js Callback Option Truy Cap 'this' De Lay Du Lieu Chart Nhung Dung Arrow Function",
     "content": "new Chart(ctx, { type: 'bar', options: { onClick: (event) => { const points = this.getElementsAtEventForMode(event, ...); console.log(points) } } }) — dung arrow function cho callback onClick, nhung Chart.js thiet ke API nay de goi callback voi 'this' tro ve chart instance (khong phai arrow function ke thua tu scope ngoai) — this.getElementsAtEventForMode nem TypeError vi 'this' ben trong arrow function la scope ben ngoai (component/module), khong phai chart instance nhu Chart.js mong doi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-012", "title": "Context Loss: Node.js EventEmitter Subclass Method Dang Ky Lam Listener Cho Chinh No",
     "content": "class Watcher extends EventEmitter { constructor() { super(); this.count = 0; this.on('tick', this.handleTick) } handleTick() { this.count++ } } — truyen this.handleTick truc tiep vao this.on() ma khong bind — moi lan emit('tick'), EventEmitter goi handleTick() nhu 1 function doc lap (EventEmitter khong tu dong bind this cho listener), 'this' ben trong handleTick khong con la Watcher instance, this.count++ that bai hoac tao property sai cho.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-013", "title": "Context Loss: Sequelize Model Instance Method Truyen Lam Callback Cho Array reduce",
     "content": "class Invoice extends Model { calculateLineTotal(item) { return item.qty * this.taxRate } } const invoice = await Invoice.findByPk(1); const total = invoice.items.reduce(invoice.calculateLineTotal, 0) — truyen invoice.calculateLineTotal truc tiep vao reduce() lam accumulator function tach method khoi Sequelize model instance — this.taxRate (thuoc tinh cua model) khong con truy cap duoc ben trong calculateLineTotal khi duoc goi boi reduce(), gay ket qua tinh toan sai hoac loi runtime.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-014", "title": "Context Loss: Electron IPC Handler Class Method Dang Ky Truc Tiep Cho ipcMain.handle",
     "content": "class FileManager { constructor(basePath) { this.basePath = basePath } async readFile(event, filename) { return fs.readFile(path.join(this.basePath, filename), 'utf8') } registerHandlers() { ipcMain.handle('read-file', this.readFile) } } — dang ky this.readFile truc tiep cho ipcMain.handle ma khong bind — khi renderer process goi IPC 'read-file', Electron goi handler nhu function doc lap, 'this' ben trong readFile khong con la FileManager instance, this.basePath la undefined, path.join() nem TypeError ngay khi co request IPC dau tien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b2-clt-015", "title": "Context Loss: Setter/Getter Method Cua Class Duoc Trich Xuat De Dung Trong Object.defineProperty O Noi Khac",
     "content": "class Temperature { constructor() { this._celsius = 0 } get fahrenheit() { return this._celsius * 9/5 + 32 } set fahrenheit(f) { this._celsius = (f - 32) * 5/9 } } const temp = new Temperature(); const { get, set } = Object.getOwnPropertyDescriptor(Temperature.prototype, 'fahrenheit'); Object.defineProperty(someOtherObj, 'temp', { get, set }) — gan getter/setter cua Temperature sang someOtherObj khien 'this' ben trong luc goi someOtherObj.temp tro ve someOtherObj (khong co _celsius) thay vi instance Temperature goc, doc/ghi tra ve gia tri sai hoan toan (NaN) ma khong nem loi ro rang.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch2, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
