"""
AI2 — batch 1 mo rong KB: viet tay 15 doc/pattern cho 3 pattern mong nhat con lai
sau round 1/2 (zalgo:10, double_callback:10, promise_no_await:9). Moi doc la 1
tinh huong code CU THE khac nhau that su (ten ham, thu vien, boi canh khac nhau),
khong dung khuon cau lap lai — dung yeu cau "khong trung nhau, rieng biet".

Muc tieu thuc te: ~45 doc batch nay (khong phai 5000 dong loat — xem RESEARCH_LOG
ghi chu tradeoff quy mo vs chat luong).

Chay: python add_batch1_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ================= ZALGO (15 doc, tinh huong khac nhau) =================
    {"id": "js-b1-zalgo-001", "title": "Zalgo: Cache Hit Tra Ve Dong Bo, Cache Miss Tra Ve Bat Dong Bo",
     "content": "Ham getUser(id, cb) kiem tra Map cache truoc: neu co thi goi cb(cache.get(id)) ngay lap tuc (dong bo), neu khong co thi goi db.query() roi cb trong .then() (bat dong bo). Code goi getUser hai lan lien tiep voi cung id se thay lan dau (cache miss) log sau cac dong code tiep theo, lan hai (cache hit) log truoc — thu tu log dao lon tuy trang thai cache, gay bug rat kho debug khi viet unit test dua vao thu tu console.log.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-002", "title": "Zalgo: Validate Input Dong Bo Nhung Goi API Ngoai Bat Dong Bo",
     "content": "Middleware validateAndFetch(req, res, next) kiem tra req.body.email hop le bang regex — neu sai thi goi next(err) ngay (dong bo); neu dung thi goi fetch() toi service xac thuc email that va goi next() trong .then() (bat dong bo). Cac middleware Express phia sau gia dinh next() luon duoc goi bat dong bo (qua process.nextTick tu Express), nhung nhanh loi dong bo pha vo gia dinh do, co the khien res duoc gui truoc khi cac middleware logging phia truoc kip chay xong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-003", "title": "Zalgo: EventEmitter Emit Ngay Neu Da San Sang, Cho Bat Dong Bo Neu Chua",
     "content": "Class Connection extends EventEmitter co method whenReady(cb) — neu this.ready === true thi goi cb() ngay trong cung tick (dong bo); neu chua thi this.once('ready', cb) (bat dong bo, cho event loop tiep theo). Code dang ky nhieu listener qua whenReady() se thay listener dau tien (luc chua ready) chay sau cac dong code phia sau loi goi, nhung listener dang ky sau (luc da ready) chay truoc — thu tu callback khong nhat quan giua cac lan goi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-004", "title": "Zalgo: Ham Doc Config Tu File Luc Dau (Sync) Sau Do Tu Redis (Async)",
     "content": "Ham loadConfig(key, cb) trong giai doan khoi dong app doc tu file JSON local bang fs.readFileSync roi goi cb() ngay (dong bo); sau khi app chuyen sang che do 'live', cung ham nay doc tu Redis qua redisClient.get() bat dong bo. Code goi loadConfig() trong route handler co the nhan callback dong bo hay bat dong bo tuy vao thoi diem server dang o giai doan nao, dan den thu tu xu ly request bi dao lon khong the du doan trong giai doan chuyen tiep.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-005", "title": "Zalgo: Thu Vien Third-Party Callback Dong Bo Khi Co Loi Validation, Bat Dong Bo Khi Thanh Cong",
     "content": "Thu vien upload xu ly file(file, cb): neu file vuot kich thuoc gioi han thi goi cb(new Error('too large')) ngay lap tuc truoc khi bat dau upload (dong bo); neu hop le thi bat dau upload qua network va goi cb(null, url) trong callback cua request (bat dong bo). Code goi upload() dang gia dinh luon co the dang ky '.on(error)' truoc khi loi xay ra, nhung nhanh loi dong bo khien cb duoc goi truoc khi code kip gan handler, bo lot loi trong mot so truong hop.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-006", "title": "Zalgo: Ham Tinh Toan Tra Ve Truc Tiep Neu Nho, Offload Worker Thread Neu Lon",
     "content": "Ham processData(data, cb) kiem tra data.length: neu nho hon 1000 thi tinh toan truc tiep va goi cb(result) ngay (dong bo, chay tren main thread); neu lon hon thi gui sang worker_threads va goi cb trong 'message' handler (bat dong bo). Ung dung goi processData() lien tuc trong vong lap voi kich thuoc data thay doi se co callback chay xen ke dong bo/bat dong bo khong theo thu tu du doan duoc, gay kho khan khi debug performance.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-007", "title": "Zalgo: Logger Ghi File Dong Bo O Development, Bat Dong Bo O Production",
     "content": "Module logger.write(msg, cb) dung fs.appendFileSync + goi cb() ngay khi NODE_ENV === 'development' (de log hien thi ngay khi debug), nhung dung fs.appendFile bat dong bo khi production (de khong chan event loop). Code phu thuoc vao thu tu log (vi du test integration kiem tra thu tu dong log) se pass o development nhung fail ngau nhien o production do thu tu ghi log khong con dam bao giong nhu luc dev.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-008", "title": "Zalgo: Middleware Auth Kiem Tra Token Local Truoc, Goi API External Neu Can",
     "content": "Middleware checkAuth(req, res, next) kiem tra JWT trong local cache truoc — neu con han thi goi next() ngay (dong bo, khong I/O); neu het han hoac khong co thi goi authService.verify() qua network va goi next() trong .then() (bat dong bo). Test integration viet gia dinh middleware luon bat dong bo (dung setImmediate de doi) se bi flaky: request voi token con han se hoan tat truoc ca khi test kip gan expectation, khien assertion chay tren state cu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-009", "title": "Zalgo: Ham Retry Goi Lai Ngay Neu Loi Mang Cu Con, Cho Backoff Neu Loi Moi",
     "content": "Ham fetchWithRetry(url, cb) kiem tra 1 bien global lastErrorTime — neu loi gan day (duoi 100ms) thi retry ngay lap tuc trong cung tick (dong bo ve mat thu tu goi); neu loi da lau hoac lan dau thi cho setTimeout backoff roi moi retry (bat dong bo). Code goi song song nhieu fetchWithRetry() cho nhieu URL khac nhau se co thu tu hoan thanh khong nhat quan giua cac lan chay do phu thuoc vao trang thai loi gan nhat cua toan cuc, khong phai cua tung URL rieng.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-010", "title": "Zalgo: Ham Parse JSON Tra Ve Ngay Neu String Ngan, Dung Stream Parser Neu Dai",
     "content": "Ham parseLargeJSON(str, cb) kiem tra str.length: neu duoi 10000 ky tu thi JSON.parse() truc tiep va goi cb(result) dong bo; neu vuot nguong thi dung stream-json bat dong bo de tranh chan event loop voi payload lon. He thong log/monitoring ben ngoai dung thu tu callback de doi chieu voi thu tu request se gap sai lech khi payload dao dong quanh nguong 10000 ky tu, vi cung 1 endpoint co the tra ve callback dong bo hoac bat dong bo tuy request.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-011", "title": "Zalgo: Ham Doc File Config Dung fs.existsSync De Quyet Dinh Duong Sync/Async",
     "content": "Ham getSetting(key, cb) goi fs.existsSync('./local-override.json') truoc — neu file ton tai thi doc bang readFileSync va goi cb() ngay (dong bo); neu khong thi fetch tu remote config server bat dong bo. Trong moi truong CI, file override thuong duoc tao tam thoi boi 1 test truoc do va bi xoa giua chung, khien cung 1 doan code test co the nhan callback dong bo hay bat dong bo tuy thu tu chay test — gay flaky test kho tai hien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-012", "title": "Zalgo: Rate Limiter Tra Ve Ngay Neu Con Quota, Cho Bat Dong Bo Neu Het",
     "content": "Middleware rateLimiter(req, res, next) kiem tra Map luu quota trong memory: neu con quota thi tru 1 va goi next() ngay (dong bo); neu het quota thi phai query Redis de kiem tra sliding window that va goi next()/res.status(429) trong Promise (bat dong bo). Cac request lien tiep tu cung 1 user co the duoc xu ly khong theo dung thu tu gui den do 1 so request 'di duong tat' dong bo con so khac phai cho Redis, gay hien tuong request gui sau lai duoc phan hoi truoc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-013", "title": "Zalgo: Ham Validate Schema Dung Cache Compiled Validator Dong Bo, Compile Lan Dau Bat Dong Bo",
     "content": "Ham validate(schema, data, cb) kiem tra validatorCache.has(schema.id) — neu co san (da compile truoc do) thi validator.validate(data) chay dong bo va goi cb() ngay; neu chua co thi phai compile schema (thao tac nang, duoc day sang setImmediate de khong chan event loop) roi moi validate va goi cb bat dong bo. Request dau tien voi 1 schema moi se co hanh vi callback khac han cac request sau do voi cung schema, gay kho hieu khi viet test end-to-end dua theo thu tu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-014", "title": "Zalgo: Ham Ghi Metric Dung Buffer In-Memory Dong Bo, Flush Ra Disk Bat Dong Bo",
     "content": "Ham recordMetric(name, value, cb) day metric vao buffer array va goi cb() ngay lap tuc (dong bo) — nhung khi buffer day (vi du 1000 item), no trigger flushToDisk() bat dong bo va cb cua lan goi do chi duoc goi SAU KHI flush xong. Code goi recordMetric() lien tuc trong vong lap se thay hau het cb chay dong bo, nhung dinh ky co 1 lan cb bi tre dang ke do trung thoi diem flush — gay do tre khong deu rat kho phat hien qua test thong thuong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},
    {"id": "js-b1-zalgo-015", "title": "Zalgo: SDK Client Goi Callback Dong Bo Khi Offline-Mode, Bat Dong Bo Khi Online",
     "content": "SDK analytics.track(event, cb) kiem tra navigator.onLine (hoac tuong duong o Node qua flag config): neu offline-mode thi luu event vao localStorage/file va goi cb() ngay (dong bo); neu online thi gui qua network va goi cb trong response callback (bat dong bo). Ung dung Electron chuyen doi giua online/offline khi mat mang tam thoi se co hanh vi callback khac nhau giua cac lan goi track() lien tiep trong cung 1 ham, du code goi khong thay doi gi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta zalgo)", "url": "", "pattern_ids": ["zalgo"]},

    # ============= DOUBLE_CALLBACK (15 doc) =============
    {"id": "js-b1-dc-001", "title": "Double Callback: Middleware Goi next() Ca Trong Try Va Catch",
     "content": "Middleware Express asyncHandler(req, res, next) co try { await doWork(); next() } catch (e) { logError(e); next() } — thieu return truoc next() trong catch, nen neu doWork() throw sau khi da goi 1 phan cua next() (vi du next duoc goi trong nhanh khac truoc do do logic sai), next() bi goi 2 lan, Express warning 'Cannot set headers after they are sent' xuat hien ngau nhien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-002", "title": "Double Callback: Ham Doc File Goi cb Trong Ca stat Va readFile Loi",
     "content": "function readSafe(path, cb) { fs.stat(path, (err, stat) => { if (err) cb(err); fs.readFile(path, (err2, data) => { if (err2) cb(err2); cb(null, data) }) }) } — thieu 'return' sau moi lan cb(err), nen neu stat loi, code van tiep tuc goi fs.readFile (voi path co the khong ton tai), roi lai goi cb them lan nua khi readFile cung loi — caller nhan callback 2 lan voi 2 error khac nhau cho cung 1 request.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-003", "title": "Double Callback: Timeout Race Voi Ham Async Khong Huy Duoc",
     "content": "function withTimeout(promiseFn, ms, cb) { const timer = setTimeout(() => cb(new Error('timeout')), ms); promiseFn().then(result => cb(null, result)) } — khong clearTimeout(timer) sau khi promiseFn() thanh cong, nen neu promiseFn() hoan tat dung luc timeout cung kich hoat, cb duoc goi 2 lan: 1 lan voi ket qua thanh cong, 1 lan voi loi timeout — code goi ham nhan ca 2, khong biet tin cai nao.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-004", "title": "Double Callback: Event Listener Khong Remove Sau Khi Da Nhan Ket Qua",
     "content": "function waitForConnection(socket, cb) { socket.on('connect', () => cb(null)); socket.on('error', (e) => cb(e)) } — neu socket phat ca 2 event 'connect' roi sau do 'error' (vi du mat ket noi ngay sau khi vua connect), cb duoc goi 2 lan vi listener khong bi go bo sau lan goi dau. Fix can dung socket.once() thay vi .on(), hoac tu remove listener ngay trong callback.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-005", "title": "Double Callback: Ham Xu Ly Upload Goi Callback O Ca 'Loi Validate' Va 'Xong Upload'",
     "content": "function handleUpload(file, cb) { if (file.size > MAX) cb(new Error('too big')); uploadToS3(file, (err, url) => cb(err, url)) } — thieu return sau cb loi kich thuoc, nen code van tiep tuc goi uploadToS3() du file da qua lon, va khi upload xong (thanh cong hoac loi) cb duoc goi them lan nua — file qua lon van bi upload len S3 tinh phi du da bao loi truoc do.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-006", "title": "Double Callback: Retry Logic Goi Callback O Moi Lan Thu Thay Vi Chi Lan Cuoi",
     "content": "function fetchWithRetry(url, retries, cb) { request(url, (err, res) => { if (err && retries > 0) return fetchWithRetry(url, retries - 1, cb); cb(err, res) }) } — code nay dung, NHUNG neu logic sua sai (vi du xoa nham 'return' truoc de goi de quy), moi lan retry deu goi cb them 1 lan thay vi chi lan cuoi cung — caller nhan N callback cho 1 request co N lan retry, gay xu ly ket qua trung lap nhieu lan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-007", "title": "Double Callback: Ham Validate Schema Goi cb O Ca Vong Lap Loi Va Sau Vong Lap",
     "content": "function validateFields(fields, cb) { for (const f of fields) { if (!f.valid) cb(new Error(`${f.name} invalid`)) } cb(null, 'all valid') } — thieu return trong vong lap, nen neu co nhieu hon 1 field khong hop le, cb duoc goi 1 lan cho MOI field loi, roi con goi them 1 lan 'all valid' sau vong lap du co loi — caller nhan nhieu callback mau thuan nhau (bao loi roi lai bao thanh cong).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-008", "title": "Double Callback: Wrapper Around Callback-Based Library Khong Guard Duplicate Call",
     "content": "function promisify_manual(fn) { return (...args) => new Promise((resolve, reject) => { fn(...args, (err, result) => { if (err) reject(err); resolve(result) }) }) } — thieu return truoc resolve(result), nen neu thu vien goc (fn) vi 1 ly do nao do goi callback goc 2 lan (chinh no co bug double-callback), Promise co the resolve roi lai co gang resolve/reject lan nua — JavaScript Promise se bo qua lan goi thu 2 mot cach am tham (khong throw loi), che giau bug that su cua thu vien goc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-009", "title": "Double Callback: Cron Job Goi Callback Hoan Tat O Ca 2 Nhanh Try/Finally",
     "content": "cron.schedule('* * * * *', () => { try { doTask(onComplete) } finally { onComplete() } }) — neu doTask() da goi onComplete() khi thanh cong (trong try), block finally van goi onComplete() them 1 lan nua vi finally luon chay bat ke try co loi hay khong — logic ghi log 'job completed' hoac gui thong bao se chay 2 lan cho 1 lan chay cron that su.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-010", "title": "Double Callback: GraphQL Resolver Goi callback() Trong DataLoader Va Truc Tiep",
     "content": "Resolver dung dataloader.load(id).then(cb) nhung ben trong batch function cua DataLoader lai vo tinh goi truc tiep cb(result) o 1 nhanh loi truoc khi Promise cua DataLoader resolve — client GraphQL nhan 2 response cho cung 1 field trong truong hop loi, vi phat sinh 2 nguon goi callback doc lap khong duoc dong bo hoa voi nhau.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-011", "title": "Double Callback: Ham Xu Ly WebSocket Message Goi ack() O Ca Handler Va onerror",
     "content": "socket.on('message', (data) => { try { process(data); ack() } catch(e) { sendError(e); ack() } }); socket.on('error', () => ack()) — neu process(data) throw loi VA ngay sau do socket phat them event 'error' khong lien quan (vi du do mang chap chon), ack() bi goi 2 lan cho cung 1 message — he thong dem so message da xac nhan (ack count) bi tinh sai, lech so voi so message thuc te gui di.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-012", "title": "Double Callback: Queue Worker Goi done() O Ca Success Handler Va Timeout Guard",
     "content": "worker.process(async (job, done) => { const timer = setTimeout(() => done(new Error('job timeout')), 30000); const result = await handleJob(job); clearTimeout(timer); done(null, result) }) — neu handleJob() mat dung 30000ms (bien gioi timeout), ca 2 nhanh (timeout va success) co the goi done() gan nhu dong thoi truoc khi clearTimeout kip huy — BullMQ nhan 2 lan bao cao ket qua cho cung 1 job, co the danh dau job vua thanh cong vua that bai tuy thu tu xu ly.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-013", "title": "Double Callback: Test Setup (Jest) Goi done() Trong forEach Va Sau Vong Lap",
     "content": "test('all items processed', (done) => { items.forEach(item => { processItem(item, (err) => { if (err) done(err) }) }); done() }) — done() duoc goi ngay lap tuc sau forEach (vi forEach khong doi async), roi tung processItem() bat dong bo cung co the goi done(err) rieng khi co loi — Jest bao loi 'done() called multiple times' vi test framework chi cho phep goi done() dung 1 lan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-014", "title": "Double Callback: Serverless Handler (Lambda) Goi callback() Ca Trong .then Va .catch Sai Cho",
     "content": "exports.handler = (event, context, callback) => { doAsyncWork(event).then(result => callback(null, result)).catch(err => { callback(err); callback(null, 'fallback') }) } — nhanh catch goi callback() 2 lan (1 lan bao loi, 1 lan fallback ngay sau do khong co return) — AWS Lambda runtime canh bao ket qua khong xac dinh khi callback duoc goi nhieu lan, hanh vi thuc te la lan goi dau tien duoc dung, cac lan sau bi bo qua nhung van ton bo nho/log gay nhieu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},
    {"id": "js-b1-dc-015", "title": "Double Callback: Ham Wrap Callback-Style API Cu Bang setImmediate De 'Dam Bao Async' Nhung Quen Guard",
     "content": "function forceAsync(fn, cb) { let called = false; setImmediate(() => { fn((err, res) => { cb(err, res) }) }); fn.cancelFn && fn.cancelFn(() => cb(new Error('cancelled'))) } — bien 'called' duoc khai bao nhung khong dung de guard, nen neu ca 2 duong (ket qua binh thuong tu fn va cancelFn duoc goi tu ben ngoai) cung kich hoat, cb() bi goi 2 lan voi 2 loai ket qua khac nhau (1 thanh cong, 1 bao huy) — logic downstream xu ly ca 2 truong hop mau thuan nhau tren cung 1 request.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta double_callback)", "url": "", "pattern_ids": ["double_callback"]},

    # ============= PROMISE_NO_AWAIT (15 doc) =============
    {"id": "js-b1-pna-001", "title": "Missing Await: Ghi Log Audit Truoc Khi Tra Response Trong Express",
     "content": "app.post('/order', async (req, res) => { createOrder(req.body); auditLog.write({ action: 'order_created', userId: req.user.id }); res.json({ status: 'ok' }) }) — ca createOrder() va auditLog.write() la async nhung khong duoc await — response tra ve ngay ca khi order chua thuc su duoc tao trong database, client co the query lai ngay va khong thay order vua tao (stale read do race giua write va read tiep theo).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-002", "title": "Missing Await: Xoa File Tam Trong Cron Job Cleanup",
     "content": "cron.schedule('0 0 * * *', () => { const files = fs.readdirSync(tmpDir); files.forEach(f => fs.promises.unlink(path.join(tmpDir, f))) }) — fs.promises.unlink() tra ve Promise nhung khong duoc await trong forEach — cron job bao cao 'cleanup done' ngay lap tuc du cac file chua thuc su bi xoa xong, neu co loi xoa file (permission denied) se tro thanh unhandled rejection am tham, thu muc tam dan day len ma khong ai biet.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-003", "title": "Missing Await: Gui Notification Push Trong React Native Sau Khi Luu Local State",
     "content": "async function markAsRead(messageId) { setMessages(prev => prev.map(m => m.id === messageId ? {...m, read: true} : m)); notificationService.markDelivered(messageId) } — notificationService.markDelivered() la network call bat dong bo khong duoc await — neu user dong app ngay sau khi bam doc tin nhan, request markDelivered co the bi huy giua chung (do app bi kill), server khong bao gio nhan duoc xac nhan, tin nhan van hien 'chua doc' o phia server.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-004", "title": "Missing Await: Invalidate Cache Redis Sau Khi Update Database",
     "content": "async function updateProduct(id, data) { await db.products.update(id, data); redisClient.del(`product:${id}`); return { success: true } } — redisClient.del() khong duoc await — ham tra ve 'success: true' ngay ca khi cache invalidation chua chay xong, request doc san pham ngay sau do co the van nhan du lieu cu tu cache (stale cache) trong khoang thoi gian del() dang cho xu ly, gay hien tuong 'update roi nhung van thay du lieu cu'.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-005", "title": "Missing Await: Ghi Metric Analytics Trong GraphQL Resolver",
     "content": "resolvers.Mutation.createComment = async (_, args, ctx) => { const comment = await db.comments.create(args); analytics.track('comment_created', { userId: ctx.userId }); return comment } — analytics.track() la async (goi API ben ngoai) khong duoc await — resolver tra ve comment ngay, neu analytics service tra ve loi (vi du rate limit), day tro thanh unhandled rejection trong Node.js process, co the tich luy qua thoi gian va gay canh bao memory leak tu nhieu Promise chua duoc GC.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-006", "title": "Missing Await: Dong Ket Noi Database Truoc Khi Thoat CLI Script",
     "content": "async function main() { const data = await fetchData(); processData(data); db.disconnect(); console.log('Done') } — db.disconnect() la async operation (dong ket noi pool, flush buffer) khong duoc await — script CLI in ra 'Done' va Node.js process co the thoat (process.exit ngam dinh khi het viec) truoc khi disconnect thuc su hoan tat, co nguy co mat du lieu con dang buffer chua flush xong xuong disk.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-007", "title": "Missing Await: Upload File Len S3 Trong Migration Script",
     "content": "for (const record of oldRecords) { const newUrl = uploadToS3(record.filePath); db.records.update(record.id, { url: newUrl }) } — uploadToS3() la async, khong await, nen newUrl thuc te la 1 Promise object (khong phai string URL that) — db.records.update() luu nham gia tri '[object Promise]' vao truong url cho toan bo record trong migration, loi chi phat hien sau khi migration da chay xong tren production.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-008", "title": "Missing Await: Gui Email Xac Nhan Trong Queue Worker Truoc Khi Danh Dau Job Done",
     "content": "worker.process(async (job) => { const order = await processOrder(job.data); emailService.sendConfirmation(order.email, order.id); return { success: true } }) — emailService.sendConfirmation() khong duoc await — BullMQ danh dau job la 'completed' ngay ca khi email gui that bai (loi SMTP timeout), khong co co che retry cho rieng phan gui email, khach hang khong nhan duoc email xac nhan ma khong ai biet do job da bao 'thanh cong'.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-009", "title": "Missing Await: Xoa Session Redis Khi User Logout Trong WebSocket Handler",
     "content": "socket.on('logout', () => { sessionStore.destroy(socket.sessionId); socket.emit('logout_ack'); socket.disconnect() }) — sessionStore.destroy() la async (goi Redis) khong duoc await — client nhan 'logout_ack' va ngat ket noi truoc khi session thuc su bi xoa khoi Redis, neu client (hoac attacker co token cu) ket noi lai ngay lap tuc voi cung session token van co the duoc chap nhan trong khoang thoi gian ngan do session chua kip xoa.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-010", "title": "Missing Await: Ghi File Log Trong Electron Main Process Truoc Khi App Quit",
     "content": "app.on('before-quit', () => { logger.flush(); app.exit() }) — logger.flush() la async (ghi buffer log con lai xuong disk) khong duoc await — app.exit() co the chay ngay lap tuc va ket thuc process truoc khi flush() kip hoan tat, mat cac dong log cuoi cung ngay truoc khi app dong, gay kho khan khi debug crash report vi thieu dung log quan trong nhat.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-011", "title": "Missing Await: Revoke Token Cu Truoc Khi Cap Token Moi Trong Refresh Flow",
     "content": "async function refreshToken(oldToken) { tokenStore.revoke(oldToken); const newToken = await generateToken(); return newToken } — tokenStore.revoke() khong duoc await — ham tra ve token moi ngay ca khi token cu chua thuc su bi thu hoi trong database, tao ra khoang thoi gian ngan ca 2 token (cu va moi) deu hop le dong thoi, vi pham gia dinh bao mat 'chi 1 token hop le tai 1 thoi diem' cua he thong refresh token.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-012", "title": "Missing Await: Cap Nhat Elasticsearch Index Sau Khi Luu Database Trong Fastify Route",
     "content": "fastify.post('/articles', async (req, reply) => { const article = await db.articles.create(req.body); esClient.index({ index: 'articles', body: article }); return reply.send(article) }) — esClient.index() khong duoc await — response tra ve thanh cong ngay ca khi index Elasticsearch chua chay xong, nguoi dung search ngay bai viet vua tao co the khong tim thay do do tre index chua hoan tat, gay cam giac 'bai viet bi mat' du that ra da luu database thanh cong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-013", "title": "Missing Await: Ghi Nhan Su Kien Webhook Vao Database Truoc Khi Tra 200 OK",
     "content": "app.post('/webhook/stripe', (req, res) => { db.webhookEvents.insert({ type: req.body.type, data: req.body, receivedAt: new Date() }); res.sendStatus(200) }) — db.webhookEvents.insert() la async khong duoc await (va route handler khong danh dau async) — Stripe nhan HTTP 200 ngay lap tuc, nhung neu insert() that bai (vi du database tam thoi qua tai), su kien webhook bi mat vinh vien vi Stripe se khong retry (da nhan 200 OK), du server thuc te chua luu duoc gi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-014", "title": "Missing Await: Xoa File Anh Cu Khi User Upload Avatar Moi",
     "content": "async function updateAvatar(userId, newFile) { const user = await db.users.findById(userId); fs.promises.unlink(user.avatarPath); const newPath = await saveFile(newFile); await db.users.update(userId, { avatarPath: newPath }); return newPath } — fs.promises.unlink() khong duoc await — request hoan tat va tra ve newPath thanh cong ngay ca khi viec xoa file avatar cu chua chay xong (hoac that bai am tham), qua thoi gian dai file rac tich luy chiem dung dung luong luu tru ma khong co canh bao nao xuat hien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b1-pna-015", "title": "Missing Await: Broadcast Thay Doi Trang Thai Qua SSE Sau Khi Cap Nhat In-Memory State",
     "content": "function updateGameState(roomId, newState) { gameRooms.set(roomId, newState); sseClients.get(roomId)?.forEach(client => client.notifyAsync(newState)) } — client.notifyAsync() la async (ghi vao SSE stream, co the can flush buffer network) nhung khong duoc await trong forEach — ham updateGameState() (goi dong bo tu noi khac) tra ve ngay lap tuc du cac client chua chac chan da nhan duoc trang thai moi, neu co loi ghi stream (client da disconnect) se tro thanh unhandled rejection rai rac khap noi trong log, kho truy vet nguon goc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch1, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
