"""
AI2 — batch 3 mo rong KB: viet tay 15 doc/pattern cho 3 pattern mong tiep theo
sau batch 1/2 (unhandled_rejection:32, sequential_awaits:48, singleton_lazy_init:49).
Moi doc la 1 tinh huong code CU THE khac nhau that su, khong dung khuon cau lap lai.

Chay: python add_batch3_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ============= UNHANDLED_REJECTION (15 doc) =============
    {"id": "js-b3-ur-001", "title": "Unhandled Rejection: Fire-and-Forget Promise Trong Express Middleware Logging",
     "content": "app.use((req, res, next) => { analyticsClient.logRequest(req.path); next() }) — analyticsClient.logRequest() tra ve Promise (goi API ngoai) nhung khong duoc await/catch — neu API analytics tra ve loi (rate limit, timeout), Promise reject ma khong ai xu ly, Node.js in UnhandledPromiseRejectionWarning ra console; tu Node 15+ neu khong co process-level handler, warning nay co the escalate thanh crash toan bo server.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-002", "title": "Unhandled Rejection: setTimeout Callback Goi Ham Async Ma Khong Bat Loi",
     "content": "setTimeout(async () => { await syncDataToRemote() }, 60000) — arrow function truyen vao setTimeout la async nhung setTimeout khong quan tam den gia tri tra ve (Promise) cua callback — neu syncDataToRemote() reject, khong co .catch() nao bat duoc no vi setTimeout khong await callback, Promise reject 'roi tu do' thanh unhandled rejection moi 60 giay neu loi lap lai (vi du server dich chet tam thoi).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-003", "title": "Unhandled Rejection: EventEmitter Listener Async Throw Loi Khong Duoc Bat",
     "content": "eventBus.on('order.created', async (order) => { await sendConfirmationEmail(order) }) — EventEmitter.emit() goi listener dong bo, khong biet va khong quan tam listener co phai la async function hay khong — neu sendConfirmationEmail() reject, EventEmitter khong co co che bat loi nay (khac voi Promise.then), Promise tro thanh unhandled rejection, loi gui email that bai bi 'nuot' hoan toan, khong ai duoc thong bao.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-004", "title": "Unhandled Rejection: Promise.all Voi 1 Phan Tu Reject Nhung Ket Qua Khong Duoc Await O Noi Goi",
     "content": "function warmupCaches() { Promise.all([cacheA.preload(), cacheB.preload(), cacheC.preload()]) } warmupCaches() — ham warmupCaches() goi Promise.all() nhung khong return no, va noi goi warmupCaches() cung khong await — neu BAT KY 1 trong 3 preload() reject, toan bo Promise.all() reject ngay lap tuc, nhung vi khong ai await/catch (ca trong ham lan noi goi), day tro thanh unhandled rejection duy nhat che giau viec ca 3 cache co the chua duoc preload day du.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-005", "title": "Unhandled Rejection: Constructor Class Goi Ham Async De Khoi Tao Nhung Khong The Await Trong Constructor",
     "content": "class DatabaseConnection { constructor(config) { this.ready = false; this.connect(config) } async connect(config) { this.client = await createClient(config); this.ready = true } } — constructor khong the la async (JavaScript khong cho phep), nen this.connect() duoc goi 'buong troi' — neu createClient() reject (config sai, network loi), Promise nay khong bao gio duoc ai await/catch, tro thanh unhandled rejection ngay tu buoc khoi tao object, code ben ngoai van coi nhu object da duoc tao thanh cong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-006", "title": "Unhandled Rejection: Array.forEach Voi Async Callback Khi 1 Item Reject Giua Chung",
     "content": "orders.forEach(async (order) => { await processRefund(order) }) — forEach khong doi Promise cua callback (da biet la anti-pattern missing_join), NHUNG con them 1 van de rieng: neu processRefund() reject cho 1 order cu the, khong co cach nao de .catch() no vi forEach khong tra ve mang Promise nhu map() — moi order that bai deu tao ra 1 unhandled rejection rieng le, khong the biet order nao that bai neu khong doc rat ky log.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-007", "title": "Unhandled Rejection: Retry Wrapper Voi setInterval Goi Ham Async Lap Lai",
     "content": "const timer = setInterval(async () => { await pollQueue() }, 5000); process.on('SIGTERM', () => clearInterval(timer)) — moi lan interval kich hoat, callback async duoc goi nhung setInterval khong lien ket voi Promise tra ve — neu pollQueue() reject o 1 chu ky bat ky (vi du mat ket noi Redis tam thoi), unhandled rejection xay ra MOI 5 giay cho den khi loi duoc khac phuc, co the lam ngap log server bang hang tram canh bao trung lap trong thoi gian ngan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-008", "title": "Unhandled Rejection: Middleware Error Handler Chinh No La Async Va Co The Reject",
     "content": "app.use(async (err, req, res, next) => { await logErrorToService(err); res.status(500).json({ error: 'Internal error' }) }) — day la error-handling middleware (4 tham so) cua Express, ban than no la async — Express KHONG await middleware nay, nen neu logErrorToService() (goi API log ngoai) reject, loi nay lai tro thanh 1 unhandled rejection MOI, xay ra ngay trong luc dang co gang xu ly 1 loi khac — 'loi chong loi' kho debug vi log the hien khong ro nguon goc that su.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-009", "title": "Unhandled Rejection: Getter Property Tra Ve Promise Duoc Dung Nhu Gia Tri Dong Bo",
     "content": "class LazyConfig { get settings() { return fetchRemoteConfig() } } const config = new LazyConfig(); if (config.settings.enabled) { ... } — settings la 1 getter tra ve Promise (fetchRemoteConfig la async), nhung code goi dung nhu the no la gia tri dong bo — config.settings.enabled luon la undefined (truy cap property tren Promise object), va Promise tu getter nay khong bao gio duoc gan vao dau ca, neu no reject se thanh unhandled rejection ma khong ai lien tuong duoc do getter 'trong nhu' 1 property binh thuong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-010", "title": "Unhandled Rejection: Chuoi .then() Thieu .catch() O Cuoi Cung Cua Promise Chain",
     "content": "fetchUser(id).then(user => fetchOrders(user.id)).then(orders => fetchInvoices(orders)).then(invoices => renderInvoices(invoices)) — chuoi .then() nay khong co .catch() o cuoi — neu BAT KY buoc nao trong chuoi reject (fetchUser, fetchOrders, fetchInvoices, hoac ngay ca renderInvoices throw loi), loi do se lan truyen qua het cac .then() con lai (bi bo qua) va cuoi cung roi vao trang thai unhandled rejection, khong co thong bao loi nao hien thi cho user, giao dien 'dung im' ma khong ro ly do.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-011", "title": "Unhandled Rejection: WebSocket onmessage Handler Async Ma Khong Wrap Try/Catch",
     "content": "ws.on('message', async (data) => { const parsed = JSON.parse(data); await handleCommand(parsed) }) — neu data khong phai JSON hop le, JSON.parse() throw loi dong bo BEN TRONG mot async function — dieu nay tu dong bien loi throw thanh 1 Promise bi reject (dac diem cua async function), nhung vi 'message' handler khong duoc goi voi await/catch tu EventEmitter, day tro thanh unhandled rejection ngay ca voi loi tuong nhu don gian la JSON parse sai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-012", "title": "Unhandled Rejection: React useEffect Goi Ham Async IIFE Nhung Khong Bat Loi",
     "content": "useEffect(() => { (async () => { const data = await fetchData(id); setData(data) })() }, [id]) — IIFE async duoc goi 'fire-and-forget' ben trong useEffect (buoc phai lam vay vi useEffect khong the tra ve Promise truc tiep) — neu fetchData() reject (vi du AbortError khi component unmount giua chung, hoac loi network that su), khong co .catch() nao duoc gan cho IIFE nay, gay unhandled rejection warning trong console trinh duyet moi lan fetch that bai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-013", "title": "Unhandled Rejection: Queue Worker Concurrency Cao Goi Ham Xu Ly Ma Khong Bat Loi Tung Job Rieng",
     "content": "for (let i = 0; i < 10; i++) { worker.processNext() } async function processNext() { const job = await queue.pop(); await handleJob(job) } — vong lap khoi tao 10 'worker loop' song song bang cach goi processNext() 10 lan ma khong await tung lan goi — day la fire-and-forget co chu dich (de chay song song), nhung neu handleJob() reject cho 1 job cu the trong 1 trong 10 loop, khong co .catch() nao bat, unhandled rejection xay ra va co the lam dung han loop worker do (tuy Node.js version xu ly the nao voi loi trong async loop khong bat).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-014", "title": "Unhandled Rejection: Module-Level Top-Level Await Trong File Config Khoi Dong",
     "content": "// config.js const settings = await loadRemoteSettings(); export default settings; // server.js import settings from './config.js' — file config.js dung top-level await (ho tro tu ES modules) de load config luc import — neu loadRemoteSettings() reject (server config khong phan hoi luc app khoi dong), day la 1 dang unhandled rejection dac biet: toan bo qua trinh import module that bai, server khong khoi dong duoc va thong bao loi co the rat kho hieu vi khong ro loi tu dau trong stack trace cua module loading.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},
    {"id": "js-b3-ur-015", "title": "Unhandled Rejection: Ham Debounce Custom Wrap Callback Async Ma Khong Truyen Loi Ra Ngoai",
     "content": "function debounce(fn, ms) { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms) } } const debouncedSave = debounce(async (data) => { await api.save(data) }, 500) — ham debounce() generic nay khong biet fn co the la async — khi setTimeout goi fn(...args) (chinh la async function api.save wrapper), Promise tra ve bi bo qua hoan toan boi setTimeout (giong loi da thay o js-b3-ur-002 nhung o day la do 1 utility function chung, kho phat hien hon vi debounce duoc dung o nhieu noi khac nhau trong codebase).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta unhandled_rejection)", "url": "", "pattern_ids": ["unhandled_rejection"]},

    # ============= SEQUENTIAL_AWAITS (15 doc) =============
    {"id": "js-b3-sa-001", "title": "Sequential Awaits: Fetch 3 API Doc Lap De Ghep Thanh Dashboard Nhung Await Tung Cai",
     "content": "async function loadDashboard(userId) { const profile = await fetchProfile(userId); const orders = await fetchOrders(userId); const notifications = await fetchNotifications(userId); return { profile, orders, notifications } } — ca 3 ham fetch* khong phu thuoc ket qua cua nhau (deu chi can userId), nhung bi await tuan tu — neu moi call mat 200ms, tong thoi gian la 600ms thay vi ~200ms neu chay song song, gay do tre khong can thiet cho trang dashboard duoc load moi lan user truy cap.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-002", "title": "Sequential Awaits: Validate Nhieu Field Doc Lap Bang Cac Ham Async Rieng Trong Form Submit",
     "content": "async function validateForm(data) { const emailValid = await checkEmailUnique(data.email); const usernameValid = await checkUsernameUnique(data.username); const phoneValid = await checkPhoneFormat(data.phone); return emailValid && usernameValid && phoneValid } — 3 ham kiem tra hoan toan doc lap (khong ham nao can ket qua cua ham kia) nhung chay tuan tu, moi ham goi API/database rieng — thoi gian validate form ty le thuan voi so luong field can kiem tra thay vi bang thoi gian cua field cham nhat, gay cam giac form 'lag' khi submit.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-003", "title": "Sequential Awaits: Upload Nhieu File Doc Lap Len S3 Trong Vong Lap For-Of",
     "content": "async function uploadAll(files) { const urls = []; for (const file of files) { const url = await uploadToS3(file); urls.push(url) } return urls } — for-of + await tuan tu tung file mot, du cac file hoan toan doc lap nhau khi upload — voi 10 file moi file mat 1 giay, tong thoi gian la 10 giay thay vi ~1-2 giay neu upload song song, user phai cho rat lau khi upload nhieu anh cung luc trong form.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-004", "title": "Sequential Awaits: Gui Push Notification Cho Nhieu Device Token Cua Cung 1 User Tuan Tu",
     "content": "async function notifyAllDevices(userId, message) { const tokens = await getDeviceTokens(userId); for (const token of tokens) { await pushService.send(token, message) } } — cac lan goi pushService.send() cho tung token la doc lap hoan toan (gui den device khac nhau), nhung xep tuan tu trong vong lap — user co 5 thiet bi dang nhap se nhan thong bao ray ra (delay giua cac device) thay vi gan nhu dong thoi, va tong thoi gian ham nay chay ty le voi so device thay vi co dinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-005", "title": "Sequential Awaits: Health Check Nhieu Service Phu Thuoc Doc Lap Trong Endpoint /health",
     "content": "app.get('/health', async (req, res) => { const dbOk = await checkDatabase(); const redisOk = await checkRedis(); const s3Ok = await checkS3(); res.json({ dbOk, redisOk, s3Ok }) }) — 3 health check khong phu thuoc nhau nhung chay tuan tu — endpoint /health thuong duoc load balancer/kubernetes goi rat thuong xuyen (moi vai giay) de kiem tra lien tuc, thoi gian phan hoi cham do await tuan tu co the khien health check tu timeout va bao sai la service down.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-006", "title": "Sequential Awaits: Xoa Nhieu Cache Key Doc Lap Trong Redis Sau Khi Invalidate",
     "content": "async function invalidateProductCaches(productId) { await redis.del(`product:${productId}`); await redis.del(`product:${productId}:reviews`); await redis.del(`product:${productId}:related`); await redis.del(`category:products:${productId}`) } — 4 lan goi redis.del() cho 4 key hoan toan doc lap, tuan tu tung cai — moi lan network round-trip toi Redis (du chi vai ms), tong do tre cong don khong can thiet khi co the gom vao 1 lenh DEL nhieu key hoac Promise.all cac call rieng.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-007", "title": "Sequential Awaits: Batch Job Xu Ly Tung Record Doc Lap Trong Migration Script",
     "content": "for (const record of allRecords) { const enriched = await enrichWithExternalAPI(record); await db.update(record.id, enriched) } — moi record duoc xu ly hoan toan doc lap voi cac record khac (khong co thu tu logic can thiet), nhung script chay tuan tu tung record — voi 10000 record, moi record mat 100ms cho API call, tong thoi gian chay migration la ~16 phut thay vi co the giam xuong vai chuc giay neu xu ly theo batch song song co gioi han concurrency.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-008", "title": "Sequential Awaits: GraphQL Resolver Fetch Nhieu Field Con Doc Lap Cua 1 Object Type",
     "content": "resolvers.User = { posts: async (user) => await fetchPosts(user.id), followers: async (user) => await fetchFollowers(user.id), likes: async (user) => await fetchLikes(user.id) } — day THUC RA la pattern dung (GraphQL tu dong goi cac field resolver song song khi co the), NHUNG neu 1 resolver cha goi TAT CA field con thu cong tuan tu (await this.posts(); await this.followers(); await this.likes()) thay vi de GraphQL engine tu dieu phoi, se mat di loi ich song song von co cua GraphQL resolver.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-009", "title": "Sequential Awaits: Test Setup (Jest beforeEach) Seed Nhieu Bang Database Doc Lap Tuan Tu",
     "content": "beforeEach(async () => { await seedUsers(); await seedProducts(); await seedCategories(); await seedSettings() }) — 4 ham seed cho 4 bang hoan toan doc lap (khong co foreign key rang buoc giua chung trong test nay), nhung chay tuan tu truoc MOI test case — voi hang tram test trong suite, tong thoi gian setup cong don rat lon, lam CI pipeline chay lau hon nhieu so voi can thiet neu seed song song bang Promise.all.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-010", "title": "Sequential Awaits: Resize Nhieu Kich Thuoc Anh Doc Lap Sau Khi Upload (Thumbnail Generation)",
     "content": "async function generateThumbnails(imagePath) { const small = await resizeImage(imagePath, 100); const medium = await resizeImage(imagePath, 300); const large = await resizeImage(imagePath, 800); return { small, medium, large } } — 3 lan resize doc lap (cung anh nguon, kich thuoc khac nhau, khong phu thuoc ket qua cua nhau) nhung chay tuan tu — voi anh lon, moi lan resize mat vai giay, tong thoi gian tao du 3 kich thuoc thumbnail ty le voi so luong kich thuoc thay vi bang thoi gian cua lan resize cham nhat.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-011", "title": "Sequential Awaits: Gui Email Cho Danh Sach Nguoi Nhan Doc Lap Trong Newsletter Job",
     "content": "async function sendNewsletter(recipients, content) { for (const recipient of recipients) { await emailService.send(recipient.email, content) } } — gui email cho tung nguoi nhan hoan toan doc lap (khong lien quan gi den nhau), nhung xep tuan tu trong vong lap — voi danh sach 1000 nguoi, moi email mat 300ms qua SMTP, tong thoi gian gui newsletter la 5 phut thay vi co the giam manh neu gui theo batch song song co gioi han (tranh bi email provider rate-limit).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-012", "title": "Sequential Awaits: Kiem Tra Ton Kho Nhieu San Pham Doc Lap Trong Gio Hang Truoc Khi Checkout",
     "content": "async function checkCartAvailability(cartItems) { for (const item of cartItems) { const inStock = await checkStock(item.productId, item.qty); if (!inStock) return false } return true } — kiem tra ton kho cho tung san pham trong gio hang la doc lap (moi san pham 1 query rieng), nhung chay tuan tu — voi gio hang co 20 san pham, thoi gian checkout cham hon dang ke so voi kiem tra song song bang Promise.all, gay trai nghiem 'loading lau' ngay truoc buoc thanh toan quan trong nhat.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-013", "title": "Sequential Awaits: Warm-Up Nhieu Model AI Doc Lap Luc Server Khoi Dong",
     "content": "async function warmupModels() { await loadModel('classifier'); await loadModel('embedder'); await loadModel('translator') } — 3 model AI hoan toan doc lap ve mat load (khong model nao can model kia load truoc), nhung load tuan tu luc server khoi dong — neu moi model mat 5 giay de load vao memory, server can 15 giay de san sang thay vi ~5 giay neu load song song, keo dai thoi gian downtime khi deploy/restart service.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-014", "title": "Sequential Awaits: Doc Nhieu File Config Doc Lap Tu Nhieu Duong Dan Khac Nhau",
     "content": "async function loadAllConfigs() { const dbConfig = await fs.promises.readFile('./config/db.json', 'utf8'); const apiConfig = await fs.promises.readFile('./config/api.json', 'utf8'); const cacheConfig = await fs.promises.readFile('./config/cache.json', 'utf8'); return { dbConfig, apiConfig, cacheConfig } } — doc 3 file config doc lap tu disk tuan tu — du moi lan doc file (I/O) chi mat vai ms, viec cong don khong can thiet nay van the hien sai tu duy — cach viet dung la Promise.all cac lan doc file de tan dung I/O song song cua he dieu hanh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},
    {"id": "js-b3-sa-015", "title": "Sequential Awaits: Tinh Toan Gia Tri Bao Cao Tu Nhieu Nguon Du Lieu Doc Lap Trong Analytics Dashboard",
     "content": "async function buildReport(dateRange) { const revenue = await calculateRevenue(dateRange); const userGrowth = await calculateUserGrowth(dateRange); const churnRate = await calculateChurnRate(dateRange); const avgOrderValue = await calculateAOV(dateRange) } — 4 phep tinh toan bao cao hoan toan doc lap (moi ham truy van du lieu rieng tu database), nhung chay tuan tu — bao cao dashboard cho quan ly mat thoi gian tai gap 4 lan so voi can thiet, dac biet gay kho chiu khi dashboard duoc refresh thuong xuyen trong ngay lam viec.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta sequential_awaits)", "url": "", "pattern_ids": ["sequential_awaits"]},

    # ============= SINGLETON_LAZY_INIT (15 doc) =============
    {"id": "js-b3-sli-001", "title": "Singleton Lazy Init: Database Connection Pool Khoi Tao Lazy Khi Co Request Dau Tien",
     "content": "let pool = null; function getPool() { if (!pool) { pool = createPool(config) } return pool } app.get('/data', async (req, res) => { const p = getPool(); const result = await p.query('SELECT ...'); res.json(result) }) — neu app nhan 2 request dau tien gan nhu dong thoi (thuong xay ra khi load balancer route nhieu request cung luc luc vua deploy), ca 2 co the cung thay pool la null va cung goi createPool() — tao ra 2 connection pool rieng biet thay vi 1, moi pool giu 1 tap connection rieng, lang phi tai nguyen database.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-002", "title": "Singleton Lazy Init: Cau Hinh Third-Party SDK Client Khoi Tao Lazy Async",
     "content": "let stripeClient = null; async function getStripeClient() { if (!stripeClient) { stripeClient = await initStripeWithSecrets() } return stripeClient } — initStripeWithSecrets() la async (phai fetch secret key tu vault truoc khi khoi tao) — 2 request thanh toan gan nhu dong thoi cung thay stripeClient la null, ca 2 cung goi initStripeWithSecrets(), tao 2 client rieng va co the goi vault API 2 lan khong can thiet (co the bi tinh phi hoac rate-limit).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-003", "title": "Singleton Lazy Init: Cache In-Memory Cua Danh Sach San Pham Khoi Tao Khi Truy Van Dau Tien",
     "content": "let productListCache = null; async function getProductList() { if (productListCache === null) { productListCache = await db.products.findAll() } return productListCache } — neu trang chu nhan nhieu request dong thoi ngay sau khi server khoi dong lai (vi du sau deploy), nhieu request cung thay cache la null va cung goi db.products.findAll() — gay 'thundering herd' vao database, nhieu query giong het nhau chay dong thoi lang phi tai nguyen thay vi chi 1 query duy nhat va cac request khac cho ket qua do.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-004", "title": "Singleton Lazy Init: Logger Instance Khoi Tao Lazy Trong Module Duoc Import O Nhieu Noi",
     "content": "let loggerInstance; module.exports.getLogger = function() { if (!loggerInstance) { loggerInstance = createLoggerWithFileTransport() } return loggerInstance } — createLoggerWithFileTransport() mo 1 file stream de ghi log — neu module nay duoc require() dong thoi tu nhieu file khac nhau trong qua trinh khoi dong app (Node.js module loading co the xen ke voi cac tac vu async khac), co nguy co tao nhieu instance logger cung ghi vao cung 1 file, gay xung dot ghi file hoac duplicate log entries.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-005", "title": "Singleton Lazy Init: WebSocket Server Instance Khoi Tao Lazy Trong Serverless Function",
     "content": "let wss = null; exports.handler = async (event) => { if (!wss) { wss = new WebSocketServer({ port: 8080 }) } return wss.handleUpgrade(event) } — trong moi truong serverless voi nhieu instance function chay song song (auto-scaling), moi 'cold start' instance co bien wss rieng (khong chia se memory giua cac instance) — code nay hoat dong sai hoan toan trong serverless (moi instance tao WebSocketServer rieng thay vi 1 singleton thuc su), day la loi thiet ke sai moi truong hon la race condition thuan tuy nhung cung xuat phat tu gia dinh sai ve lazy singleton.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-006", "title": "Singleton Lazy Init: Bang Tra Cuu (Lookup Table) Tinh Toan Nang Duoc Cache Lazy",
     "content": "let primeCache = null; function getPrimesUpTo(n) { if (!primeCache) { primeCache = sieveOfEratosthenes(1000000) } return primeCache.filter(p => p <= n) } — sieveOfEratosthenes() la thao tac CPU-bound nang (co the mat vai trăm ms) — trong moi truong co nhieu request goi ham nay gan nhu dong thoi luc dau (vi du nhieu tab client cung mo app), neu ham nay duoc chay trong worker_threads khac nhau, moi worker co bo nho rieng nen se tinh lai sieve nhieu lan thay vi dung chung 1 ket qua.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-007", "title": "Singleton Lazy Init: Feature Flag Client Khoi Tao Lazy Trong Middleware Duoc Goi Moi Request",
     "content": "let flagClient; app.use(async (req, res, next) => { if (!flagClient) { flagClient = await FeatureFlagSDK.init(apiKey) } req.flags = flagClient; next() }) — middleware nay chay cho MOI request — trong giai doan dau server vua khoi dong, nhieu request dau tien gan nhu dong thoi deu thay flagClient la undefined, moi request cung goi FeatureFlagSDK.init() (thuong la 1 network call toi feature flag service), tao nhieu ket noi khoi tao du thua toi service ben ngoai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-008", "title": "Singleton Lazy Init: Schema Validator Compiled Instance Cache Lazy Trong GraphQL Server Setup",
     "content": "let compiledSchema = null; function getExecutableSchema() { if (!compiledSchema) { compiledSchema = makeExecutableSchema({ typeDefs, resolvers }) } return compiledSchema } — makeExecutableSchema() la thao tac nang (parse + validate toan bo GraphQL schema) — neu ham nay duoc goi tu nhieu request handler dong thoi truoc khi lan goi dau tien kip hoan tat (dac biet neu duoc lam async trong tuong lai), co nguy co bien compiledSchema bi ghi de nhieu lan, moi lan tao 1 schema object moi thay vi tai su dung.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-009", "title": "Singleton Lazy Init: Rate Limiter Instance Voi State Noi Bo Khoi Tao Lazy Cho Moi Route Rieng",
     "content": "const limiters = {}; function getLimiterFor(routeName) { if (!limiters[routeName]) { limiters[routeName] = new RateLimiter({ windowMs: 60000, max: 100 }) } return limiters[routeName] } — day la singleton-per-key (khong phai singleton toan cuc), nhung van co cung van de: neu 2 request DAU TIEN toi CUNG 1 route moi (chua co limiter) den gan nhu dong thoi, ca 2 co the cung thay limiters[routeName] la undefined va tao 2 RateLimiter instance rieng cho cung 1 route — moi instance dem so luong rieng, lam rate limit thuc te long leo hon gap doi cau hinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-010", "title": "Singleton Lazy Init: Machine Learning Model Load Lazy Trong Lambda Handler Giua Cac Cold Start",
     "content": "let model = null; exports.handler = async (event) => { if (!model) { model = await tf.loadLayersModel('file://./model/model.json') } return model.predict(preprocessInput(event.body)) } — trong 1 Lambda instance don le, code nay dung (model duoc cache giua cac lan goi 'warm'), NHUNG neu AWS spawn nhieu Lambda instance song song de xu ly traffic tang dot bien (concurrent execution), moi instance co bien model rieng (khong chia se memory) — moi instance moi phai load lai model tu dau, gay cold-start cham cho tung instance thay vi chi 1 lan load duy nhat.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-011", "title": "Singleton Lazy Init: I18n Translation Bundle Load Lazy Khi Component Render Lan Dau",
     "content": "let translations = {}; async function getTranslations(locale) { if (!translations[locale]) { translations[locale] = await fetch(`/i18n/${locale}.json`).then(r => r.json()) } return translations[locale] } — neu nhieu component tren cung 1 trang deu goi getTranslations('vi') gan nhu dong thoi luc app khoi dong (moi component tu goi rieng, khong co coordination), cac component cung thay translations['vi'] la undefined va cung goi fetch() — nhieu request HTTP trung lap toi cung 1 file JSON, lang phi bang thong va co the gay flicker UI khi tung component nhan ket qua o thoi diem khac nhau.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-012", "title": "Singleton Lazy Init: Message Queue Consumer Connection Khoi Tao Lazy Khi Publish Message Dau Tien",
     "content": "let channel = null; async function publishMessage(queueName, data) { if (!channel) { const conn = await amqp.connect(RABBITMQ_URL); channel = await conn.createChannel() } channel.sendToQueue(queueName, Buffer.from(JSON.stringify(data))) } — neu app goi publishMessage() tu nhieu noi (nhieu route handler khac nhau) gan nhu dong thoi ngay sau khi khoi dong, nhieu request cung thay channel la null va cung ket noi RabbitMQ rieng — tao nhieu channel/connection du thua, vuot qua gioi han connection cho phep cua RabbitMQ server trong moi truong nhieu instance app.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-013", "title": "Singleton Lazy Init: Encryption Key Derivation Lazy Cache Trong Middleware Xac Thuc",
     "content": "let derivedKey = null; function verifyToken(token) { if (!derivedKey) { derivedKey = deriveKeyFromMasterSecret(MASTER_SECRET) } return jwt.verify(token, derivedKey) } — deriveKeyFromMasterSecret() la thao tac CPU nang (PBKDF2/scrypt co the mat vai chuc ms co chu dich de chong brute-force) — neu ham nay khong async nhung duoc goi tu nhieu request dong thoi (Node.js van xu ly tuan tu do don luong, nhung neu code duoc chuyen sang worker_threads de tang throughput), moi worker se tinh lai key rieng, mat di loi ich cache va lam cham xac thuc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-014", "title": "Singleton Lazy Init: Metrics Registry Prometheus Khoi Tao Lazy Trong Ham Ghi Nhan Metric",
     "content": "let registry = null; function recordRequestDuration(route, duration) { if (!registry) { registry = new prom.Registry(); registry.registerMetric(httpDurationHistogram) } httpDurationHistogram.observe({ route }, duration) } — neu nhieu request dong thoi cung goi recordRequestDuration() ngay khi server vua khoi dong, co nguy co registry bi khoi tao nhieu lan (moi lan registerMetric() lai them 1 histogram trung ten vao registry moi) — Prometheus client library co the throw loi 'metric already registered' hoac tao nhieu registry chi export metric rieng le khong day du khi scrape.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
    {"id": "js-b3-sli-015", "title": "Singleton Lazy Init: Search Index Client (Elasticsearch) Khoi Tao Lazy Trong Nhieu Serverless Function Rieng Biet Dung Chung 1 Layer",
     "content": "let esClient = null; function getEsClient() { if (!esClient) { esClient = new Client({ node: ES_URL, auth: creds }) } return esClient } // dung chung trong 1 Lambda Layer boi nhieu function search, indexProduct, deleteProduct — moi function Lambda rieng biet co container/memory rieng du dung chung code trong Layer, nen bien esClient KHONG duoc chia se giua cac function nhu ky vong 'singleton toan cuc' — moi function tu tao client rieng lan dau duoc goi, gay hieu lam ve so luong connection pool thuc te dang mo toi Elasticsearch cluster.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch3, dua tren mo ta singleton_lazy_init)", "url": "", "pattern_ids": ["singleton_lazy_init"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
