"""
AI2 — batch 8 mo rong KB: viet tay 15 doc/pattern cho 3 pattern mong nhat con
lai (resource_exhaustion:17, missing_join:17, promise_no_await:24). Moi doc la
1 tinh huong code CU THE khac nhau that su, khac cac doc round1/batch6 da co.

Chay: python add_batch8_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ============= RESOURCE_EXHAUSTION (15 doc) =============
    {"id": "js-b8-re-001", "title": "Resource Exhaustion: GraphQL Query Deeply Nested Khong Gioi Han Do Sau Gay Explosion So Luong Request Xuong DB",
     "content": "// schema cho phep query: user { posts { comments { author { posts { comments { ... } } } } } } khong gioi han do sau — moi cap long them vao nhan so luong resolver call len gap boi so item trung binh o cap do, 1 query voi 6-7 cap long co the trigger hang trieu resolver call xuong database, lam qua tai ca DB va CPU cua GraphQL server chi tu 1 request duy nhat, can dung graphql-depth-limit de chan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-002", "title": "Resource Exhaustion: WeakMap Duoc Dung Sai Thanh Map Thuong Khien Object Key Khong Bao Gio Duoc GC",
     "content": "const sessionMetadata = new Map(); function attachMetadata(sessionObj, data) { sessionMetadata.set(sessionObj, data) } — dung Map (khong phai WeakMap) de lien ket metadata voi 1 object session — Map giu strong reference toi key, nen du sessionObj khong con duoc su dung o noi nao khac trong code, Garbage Collector KHONG THE thu hoi no vi Map van tham chieu toi — sau nhieu session duoc tao/huy, memory tang dan vi cac object session 'chet' van bi Map giu lai vinh vien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-003", "title": "Resource Exhaustion: Server Chap Nhan Upload File Khong Gioi Han Kich Thuoc Toi Da Qua Multer",
     "content": "const upload = multer({ dest: 'uploads/' }); app.post('/upload', upload.single('file'), handler) — cau hinh multer khong co 'limits: { fileSize }' — client (hoac attacker) co the upload file voi kich thuoc bat ky, vi du vai chuc GB, chiem het dung luong disk server chi bang 1 request duy nhat, dong thoi qua trinh nhan du lieu upload lon cung tieu ton bang thong va memory buffer dang ke trong luc xu ly.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-004", "title": "Resource Exhaustion: Vong Lap Retry Voi Exponential Backoff Nhung Khong Co Max Delay Cap Tren Gay Cho Vo Han",
     "content": "async function retryWithBackoff(fn, attempt = 1) { try { return await fn() } catch (e) { const delay = Math.pow(2, attempt) * 1000; await sleep(delay); return retryWithBackoff(fn, attempt + 1) } } — khong co gioi han so lan thu VA khong co cap tren cho delay (Math.pow(2, attempt) tang vo han theo so lan retry) — voi service loi keo dai, sau du 20-30 lan retry, delay co the len den hang gio/hang ngay (2^30 giay), ham nay coi nhu 'treo' vo thoi han, giu tai nguyen (Promise chain, stack de quy) khong bao gio duoc giai phong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-005", "title": "Resource Exhaustion: Middleware Parse JSON Body Khong Gioi Han Kich Thuoc Payload Toi Da",
     "content": "app.use(express.json()) // khong truyen option { limit: '1mb' } — mac dinh Express dung limit '100kb', nhung neu code override thanh mot gia tri lon hoac khong dat limit ro rang trong 1 middleware custom parse body thu cong (JSON.parse(rawBody)), client co the gui payload JSON rat lon (vai chuc MB chuoi text lap lai) — server phai parse toan bo vao memory truoc khi validate, gay ap luc CPU/memory lon tu 1 request don le, de bi loi dung lam vector tan cong tu choi dich vu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-006", "title": "Resource Exhaustion: Vong Lap Generate Combinations To Hop Khong Gioi Han Dau Vao Gay Explosion Cap So Nhan",
     "content": "function generateAllCombinations(items) { if (items.length === 0) return [[]]; const [first, ...rest] = items; const withoutFirst = generateAllCombinations(rest); const withFirst = withoutFirst.map(c => [first, ...c]); return [...withoutFirst, ...withFirst] } — voi input co N phan tu, ket qua co 2^N to hop — endpoint nhan input tu user ma khong gioi han N (vi du N=30 da la hon 1 ty to hop), ham nay se tieu thu het memory va CPU truoc khi kip tra loi, gay crash server tu 1 request voi input don gian nhung khong duoc kiem soat kich thuoc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-007", "title": "Resource Exhaustion: Websocket Ping/Pong Heartbeat Khong Duoc Thiet Lap Khien Ket Noi Chet Van Chiem Tai Nguyen Vinh Vien",
     "content": "wss.on('connection', (ws) => { activeConnections.add(ws) }) // khong co ws.isAlive/ping interval — server khong bao gio kiem tra xem client co con 'song' hay khong (vi du client mat mang dot ngot ma khong gui frame 'close' dung cach) — ket noi 'zombie' nay van ton tai trong activeConnections va giu tai nguyen socket vo thoi han cho toi khi OS TCP timeout tu nhien (co the rat lau), tich luy nhieu ket noi zombie se can kiet tai nguyen server that su.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-008", "title": "Resource Exhaustion: Batch Job Load Toan Bo File CSV Vao Memory Bang String.split Thay Vi Stream Parser",
     "content": "async function processCsv(filePath) { const content = fs.readFileSync(filePath, 'utf8'); const lines = content.split('\\n'); for (const line of lines) { processLine(line.split(',')) } } — readFileSync() + split('\\n') doc TOAN BO file vao memory duoi dang 1 string khong lo, roi tao mang moi voi hang trieu phan tu string con — voi file CSV vai GB (data export lon), qua trinh nay co the vuot qua gioi han heap cua V8, gay crash 'JavaScript heap out of memory' truoc khi kip xu ly dong nao, can dung stream + csv-parser thay the.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-009", "title": "Resource Exhaustion: Service Worker Cache API Khong Co Chien Luoc Xoa Cache Cu Gay Tich Luy Vo Han Trong Storage Trinh Duyet",
     "content": "self.addEventListener('fetch', (event) => { event.respondWith(caches.open('v1').then(cache => cache.match(event.request).then(response => response || fetch(event.request).then(res => { cache.put(event.request, res.clone()); return res })))) }) — moi request MOI duoc cache vao 'v1' vinh vien, khong co logic xoa entry cu hoac gioi han kich thuoc cache — voi ung dung SPA co nhieu asset thay doi thuong xuyen (hash trong ten file build), cache tich luy them entry moi ma khong bao gio xoa entry cu, dan den storage quota cua trinh duyet bi vuot qua sau thoi gian dai su dung.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-010", "title": "Resource Exhaustion: Ham Deep Clone Object Tu Che Bang JSON.parse(JSON.stringify()) Voi Object Co Circular Reference Gay Vong Lap Vo Han",
     "content": "function deepClone(obj) { return JSON.parse(JSON.stringify(obj)) } // duoc goi voi object co circular reference (vi du node.parent tro nguoc lai chinh no) — JSON.stringify() throw 'Converting circular structure to JSON' ngay lap tuc trong truong hop don gian, NHUNG neu code tu viet ham deep clone thu cong bang de quy ma khong kiem tra da tham (visited set), circular reference se gay de quy vo han, nhanh chong lam ngap call stack va tieu ton CPU 100% truoc khi crash.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-011", "title": "Resource Exhaustion: Proxy Server Forward Toan Bo Response Body Vao Buffer Truoc Khi Gui Lai Thay Vi Pipe Truc Tiep",
     "content": "app.get('/proxy/:url', async (req, res) => { const response = await fetch(decodeURIComponent(req.params.url)); const buffer = await response.arrayBuffer(); res.send(Buffer.from(buffer)) } — thay vi pipe truc tiep stream tu response goc sang res (response.body.pipe(res) hoac tuong duong voi Node.js streams), code nay doc TOAN BO response vao buffer memory truoc — voi file lon (vi du proxy video/file download lon), moi request deu giu 1 buffer lon trong memory cho den khi gui xong, duoi tai nhieu request dong thoi se nhanh chong can kiet RAM server.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-012", "title": "Resource Exhaustion: In-Memory Session Store Khong Co TTL Tich Luy Session Da Het Han Vo Han",
     "content": "const sessions = new Map(); app.use((req, res, next) => { const sid = req.cookies.sid || generateId(); if (!sessions.has(sid)) sessions.set(sid, { data: {}, createdAt: Date.now() }); req.session = sessions.get(sid); next() }) — Map sessions khong bao gio xoa entry cu du session da het han logic (vi du qua 30 phut khong hoat dong) — moi visitor moi (bot, crawler, user khong dang nhap) deu tao 1 session moi tich luy vinh vien trong memory, khong co co che cleanup dinh ky, gay memory leak dan trong ung dung chay production lau dai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-013", "title": "Resource Exhaustion: Endpoint Search Full-Text Cho Phep Wildcard O Dau Chuoi Gay Table Scan Toan Bo Database",
     "content": "app.get('/search', async (req, res) => { const results = await db.query(`SELECT * FROM products WHERE name LIKE '%${req.query.q}%'`); res.json(results) }) — pattern 'LIKE %...%' voi wildcard o CA 2 dau khong the dung index hieu qua, buoc database phai quet toan bo bang (full table scan) — voi bang co hang trieu san pham, moi request search deu tao tai nang len CPU/IO cua database, nhieu request search dong thoi co the lam qua tai toan bo he thong database chi voi 1 tinh nang tim kiem don gian.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-014", "title": "Resource Exhaustion: Ham Tao PDF Report Giu Toan Bo Danh Sach Object Hinh Anh Trong Memory Truoc Khi Render Lan Luot",
     "content": "async function generateReport(items) { const images = await Promise.all(items.map(i => loadImageBuffer(i.imagePath))); const doc = new PDFDocument(); images.forEach((img, idx) => { doc.image(img); if (idx < images.length - 1) doc.addPage() }); doc.pipe(fs.createWriteStream('report.pdf')) } — Promise.all() tai TAT CA anh vao memory CUNG LUC truoc khi bat dau render trang nao — voi report co hang tram trang, moi trang 1 anh, tong dung luong anh trong memory cung 1 luc co the len den hang GB, thay vi tai va giai phong tung anh theo tung trang duoc render tuan tu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},
    {"id": "js-b8-re-015", "title": "Resource Exhaustion: Cron Job Chay Qua Nhanh So Voi Thoi Gian Xu Ly Thuc Te Gay Chong Lap Nhieu Instance Song Song",
     "content": "cron.schedule('*/1 * * * *', async () => { await syncLargeDataset() }) // syncLargeDataset() thuong mat 5 phut de chay xong — cron duoc dat chay moi 1 phut, nhung job thuc te mat 5 phut de hoan tat — khong co co che khoa (lock) de ngan chay chong lap, dan den nhieu instance cua CUNG job nay chay song song (co the len den 5 instance cung luc), moi instance tieu ton tai nguyen rieng, nhanh chong lam qua tai CPU/memory/database connection cua he thong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta resource_exhaustion)", "url": "", "pattern_ids": ["resource_exhaustion"]},

    # ============= MISSING_JOIN (15 doc) =============
    {"id": "js-b8-mj-001", "title": "Missing Join: Hook useEffect Fetch Nhieu Data Song Song Nhung Cleanup Function Chay Truoc Khi Fetch Xong",
     "content": "useEffect(() => { let cancelled = false; fetchUserData(userId).then(data => { if (!cancelled) setUserData(data) }); fetchUserPosts(userId).then(posts => { if (!cancelled) setPosts(posts) }); return () => { cancelled = true } }, [userId]) — day thuc te DA lam dung 'cancelled' flag de tranh set state sau unmount, NHUNG neu component re-render voi userId MOI truoc khi 2 fetch cu hoan tat, ca 2 Promise cu deu bi 'cancelled = true' set boi cleanup — nhung KHONG co gi doi 2 fetch MOI (cho userId moi) hoan tat truoc khi component coi nhu 'da san sang', UI co the hien thi trang thai trung gian sai trong khoanh khac ngan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-002", "title": "Missing Join: Ham Backup Nhieu Database Song Song Nhung Script Deploy Tiep Tuc Truoc Khi Backup Xong",
     "content": "function backupBeforeDeploy() { exec('mysqldump db1 > backup1.sql'); exec('mysqldump db2 > backup2.sql'); console.log('Backup started, proceeding with deploy...') } — exec() la bat dong bo (spawn child process), khong duoc await/callback cho hoan tat — script deploy tiep tuc CHAY NGAY (co the drop bang hoac chay migration pha huy du lieu) trong khi backup van dang chay ngam va chua chac chan da hoan tat, neu deploy that bai giua chung, ban backup co the khong day du hoac chua ton tai, mat kha nang rollback an toan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-003", "title": "Missing Join: Ham Preload Nhieu Asset Game Song Song Nhung Man Hinh Loading Bien Mat Truoc Khi Load Xong",
     "content": "function preloadGameAssets() { textures.forEach(t => loadTexture(t)); sounds.forEach(s => loadSound(s)); hideLoadingScreen(); startGame() } — loadTexture() va loadSound() la bat dong bo (network fetch cho asset), forEach khong doi hoan tat — hideLoadingScreen() va startGame() chay NGAY LAP TUC, game bat dau chay du texture/sound van dang tai, nguoi choi thay hinh anh bi vo (missing texture placeholder) hoac im lang (sound chua load xong) trong nhung giay dau tien.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-004", "title": "Missing Join: Chay Nhieu Lighthouse Audit Song Song Cho Cac URL Khac Nhau Nhung Tong Hop Report Qua Som Trong CI",
     "content": "async function runPerformanceAudits(urls) { const results = []; urls.forEach(url => { runLighthouse(url).then(r => results.push(r)) }); generatePerformanceReport(results); process.exit(0) } — runLighthouse() (async, mat vai chuc giay/URL) khong duoc doi hoan tat, forEach khong await — generatePerformanceReport(results) chay voi mang results rong, VA process.exit(0) ket thuc process NGAY LAP TUC, huy bo hoan toan cac audit dang chay ngam, CI job bao cao 'thanh cong' voi report rong khong co du lieu that.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-005", "title": "Missing Join: Ham Sync Nhieu Kho Hang Chi Nhanh Song Song Nhung Bao Cao Ton Kho Tong Truoc Khi Sync Xong",
     "content": "async function syncAllWarehouses(warehouseIds) { warehouseIds.forEach(id => syncWarehouseInventory(id)); const totalStock = await calculateTotalStock(); return totalStock } — syncWarehouseInventory() la async (goi API cua tung kho hang rieng), forEach khong doi — await calculateTotalStock() chay NGAY SAU forEach, tinh toan tong ton kho DUA TREN DU LIEU CU (chua duoc cac lan sync moi cap nhat), tra ve so lieu ton kho sai lech so voi thuc te vua duoc dong bo.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-006", "title": "Missing Join: Docker Compose Health Check Script Khoi Dong Nhieu Container Phu Thuoc Song Song Ma Khong Doi Dung Thu Tu",
     "content": "// entrypoint.sh goi qua Node.js child_process: exec('docker start redis-container'); exec('docker start db-container'); exec('docker start app-container'); console.log('All containers started') — 3 lenh docker start deu bat dong bo, khong doi container truoc san sang — app-container co the khoi dong VA co gang ket noi toi db-container/redis-container TRUOC KHI 2 container do thuc su san sang nhan ket noi (container 'started' khac voi 'ready'), gay loi ket noi that bai trong nhung giay dau tien sau khi he thong khoi dong.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-007", "title": "Missing Join: Ham Revoke Nhieu API Key Song Song Khi User Bi Khoa Tai Khoan Nhung Tra Response Truoc Khi Xong",
     "content": "app.post('/admin/ban-user/:id', (req, res) => { const apiKeys = getApiKeysForUser(req.params.id); apiKeys.forEach(key => revokeApiKey(key)); res.json({ status: 'user banned' }) } — revokeApiKey() la async (goi database/cache invalidation), forEach khong doi — response 'user banned' tra ve NGAY LAP TUC, trong khoang thoi gian cac revoke con dang chay ngam, user bi ban van co the su dung API key cua ho de goi API thanh cong, tao ra 1 khoang ho hong bao mat ngan nhung co that.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-008", "title": "Missing Join: Sinh Nhieu Bao Cao Excel Cho Nhieu Phong Ban Song Song Nhung Nen Zip Truoc Khi Cac File Ghi Xong",
     "content": "function generateAllDeptReports(depts) { depts.forEach(d => generateExcelReport(d).then(path => reportPaths.push(path))); zipAllReports(reportPaths, 'all-reports.zip') } — generateExcelReport() la async (mat vai giay de tao file Excel voi nhieu sheet), forEach khong doi hoan tat — zipAllReports() chay NGAY LAP TUC voi reportPaths con rong hoac chua day du, file zip cuoi cung thieu mat 1 so bao cao phong ban (nhung phong ban ma generateExcelReport chua kip hoan tat luc zipAllReports duoc goi).",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-009", "title": "Missing Join: Ham Warm Up Nhieu Lambda Function Song Song Truoc Traffic Cao Diem Nhung Bao Cao Ready Qua Som",
     "content": "async function warmUpLambdas(functionNames) { functionNames.forEach(name => invokeLambda(name, { warmup: true })); return { status: 'warmed up', count: functionNames.length } } — invokeLambda() la async (goi AWS SDK, co the mat vai giay do cold start), forEach khong doi — ham tra ve 'status: warmed up' NGAY LAP TUC, trong khi cac Lambda function that su van dang trong qua trinh cold start — neu traffic that su den ngay sau khi nhan duoc thong bao 'warmed up' sai lech nay, van gap do tre cold start ma he thong nghi rang da duoc lam nong truoc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-010", "title": "Missing Join: Chay Nhieu Query Song Song De Validate Foreign Key Truoc Khi Insert Nhung Insert Chay Truoc Khi Validate Xong",
     "content": "async function createOrderWithItems(order, items) { items.forEach(item => validateProductExists(item.productId)); await db.orders.insert(order); await db.orderItems.insertMany(items) } — validateProductExists() la async (query database), forEach khong doi ket qua validation — db.orders.insert() chay NGAY SAU forEach ma khong biet validation co qua hay khong (co the co productId khong ton tai), don hang duoc tao voi item tham chieu toi san pham khong ton tai trong database, vi pham tinh toan ven du lieu (referential integrity) ma logic tuong nhu da kiem tra truoc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-011", "title": "Missing Join: Ham Dong Bo Nhieu Bang Elasticsearch Index Song Song Nhung Bao Cao Hoan Tat Migration Qua Som",
     "content": "async function reindexAllTypes(types) { types.forEach(t => reindexType(t)); await notifySlack('Reindex complete for all types') } — reindexType() la async (co the mat vai phut cho index lon), forEach khong doi — notifySlack() gui thong bao 'hoan tat' NGAY LAP TUC du cac reindex van dang chay ngam — team van hanh nhan thong bao sai, co the tin tuong index da san sang va chuyen traffic search sang index moi trong khi du lieu chua day du, gay thieu ket qua tim kiem cho nguoi dung cuoi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-012", "title": "Missing Join: Ham Xoa Nhieu Bucket S3 Song Song Khi Don Dep Tai Nguyen Cloud Nhung Terraform Destroy Tiep Tuc Qua Som",
     "content": "function emptyBucketsBeforeDestroy(bucketNames) { bucketNames.forEach(name => emptyS3Bucket(name)); console.log('Buckets emptied, proceeding with terraform destroy') } — emptyS3Bucket() la async (co the mat lau voi bucket chua nhieu object, can list + delete theo batch), forEach khong doi — script tiep tuc chay 'terraform destroy' NGAY LAP TUC, terraform co the that bai vi bucket van con object (chua xoa xong) khong the xoa bucket, gay loi giua chung qua trinh destroy infrastructure va de lai state khong nhat quan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-013", "title": "Missing Join: Chay Nhieu Snapshot Test Song Song Cap Nhat File Snapshot Nhung Git Commit Chay Truoc Khi Ghi Xong",
     "content": "// script tu dong trong pre-commit hook: testFiles.forEach(f => updateSnapshot(f)); execSync('git add . && git commit --amend --no-edit') — updateSnapshot() la async (chay test va ghi file snapshot moi), forEach khong doi — git commit chay NGAY SAU forEach, co the commit CAC FILE SNAPSHOT CU (chua duoc cap nhat kip) thay vi snapshot moi, dan den commit khong dong bo voi code that su, gay confusion khi review PR thay snapshot khong khop voi thay doi code.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-014", "title": "Missing Join: Ham Precompute Nhieu Bang Xep Hang (Leaderboard) Song Song Nhung API Response Tra Ve Truoc Khi Tinh Xong",
     "content": "function refreshAllLeaderboards(categories) { categories.forEach(cat => recomputeLeaderboard(cat)); res.json({ status: 'refresh triggered' }) } — recomputeLeaderboard() la async (truy van + sap xep hang nghin ban ghi diem so), forEach khong doi — API tra ve 'refresh triggered' ngay lap tuc, nhung neu client ngay sau do goi API lay leaderboard, co the nhan duoc du lieu CU (chua duoc recompute xong) cho 1 so category trong khi cac category khac da co du lieu moi, gay hien thi khong nhat quan giua cac category tren cung 1 man hinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},
    {"id": "js-b8-mj-015", "title": "Missing Join: Ham Validate Nhieu Chu Ky So (Digital Signature) Song Song Truoc Khi Chap Nhan Giao Dich Blockchain Nhung Xu Ly Truoc Khi Validate Xong",
     "content": "function processMultiSigTransaction(signatures, tx) { const results = []; signatures.forEach(sig => verifySignature(sig, tx).then(valid => results.push(valid))); if (results.length === signatures.length) broadcastTransaction(tx) } — verifySignature() la async (thao tac crypto co the mat thoi gian), forEach khong doi — dieu kien 'results.length === signatures.length' duoc kiem tra NGAY LAP TUC (khi results con rong, 0 !== N), giao dich multi-sig KHONG duoc broadcast dung luc, hoac te hon neu logic sai o cho khac co the vo tinh broadcast truoc khi du chu ky duoc xac thuc, vi pham nghiem trong yeu cau bao mat cua giao dich multi-sig.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta missing_join)", "url": "", "pattern_ids": ["missing_join"]},

    # ============= PROMISE_NO_AWAIT (15 doc) =============
    {"id": "js-b8-pna-001", "title": "Missing Await: Cap Nhat Last Login Timestamp Trong Middleware Xac Thuc JWT",
     "content": "function authMiddleware(req, res, next) { const user = verifyToken(req.headers.token); db.users.update(user.id, { lastLoginAt: new Date() }); req.user = user; next() } — db.users.update() la async khong duoc await — middleware goi next() ngay lap tuc du update chua chay xong, neu co loi database (connection timeout) trong luc update, day tro thanh unhandled rejection am tham, va neu route handler phia sau doc lai user tu database ngay lap tuc co the thay lastLoginAt cua lan dang nhap TRUOC do thay vi lan hien tai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-002", "title": "Missing Await: Ghi Nhan Su Kien Phan Tich Hanh Vi Nguoi Dung Trong React Native Khi Bam Nut Mua Hang",
     "content": "function handlePurchase() { analytics.logEvent('purchase_initiated', { productId }); navigation.navigate('PaymentScreen') } — analytics.logEvent() thuong la async (co the ghi vao queue local truoc khi gui, hoac goi API truc tiep) khong duoc await — app dieu huong sang man hinh thanh toan NGAY LAP TUC, neu app bi kill (background task bi OS thu hoi tai nguyen tren mobile) truoc khi event kip duoc gui/luu, du lieu phan tich ve hanh vi mua hang bi mat, anh huong den do chinh xac cua bao cao conversion funnel.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-003", "title": "Missing Await: Xoa Cache CDN Cho Asset Cu Sau Khi Deploy Version Moi Trong Script CI/CD",
     "content": "async function deployNewVersion(version) { await uploadAssetsToS3(version); cdnClient.purgeCache(`/assets/${version - 1}/*`); console.log('Deploy complete') } — cdnClient.purgeCache() la async (goi API CDN provider) khong duoc await — script bao cao 'Deploy complete' va CI job ket thuc thanh cong ngay lap tuc, du purge cache chua chac chan da hoan tat, user co the tiep tuc nhan asset cu tu CDN edge server trong 1 khoang thoi gian sau deploy ma khong ai biet purge that su da xong hay chua.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-004", "title": "Missing Await: Cap Nhat Trang Thai Da Doc Cho Nhieu Thong Bao Khi User Mo Trang Notification Center",
     "content": "function openNotificationCenter() { markAllNotificationsRead(userId); renderNotificationList() } — markAllNotificationsRead() la async khong duoc await — renderNotificationList() chay NGAY LAP TUC va co the doc du lieu tu cache/state con giu trang thai 'chua doc' cu (chua duoc cap nhat kip boi markAllNotificationsRead), khien UI hien thi sai — badge so luong thong bao chua doc van hien so cu du user vua mo trang xem het.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-005", "title": "Missing Await: Ghi Log Kiem Toan Thay Doi Quyen Truy Cap Trong He Thong Quan Ly Nhan Su",
     "content": "async function updateEmployeeRole(empId, newRole, adminId) { await db.employees.update(empId, { role: newRole }); auditLogger.log({ action: 'role_change', empId, newRole, changedBy: adminId }); return { success: true } } — auditLogger.log() (ghi vao he thong audit rieng, co the la network call) khong duoc await — ham tra ve success ngay ca khi entry audit chua chac chan da duoc ghi, neu he thong audit that bai (network loi) ngay sau do, thay doi quyen truy cap QUAN TRONG nay khong co ban ghi audit trail, vi pham yeu cau compliance/bao mat trong he thong doanh nghiep.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-006", "title": "Missing Await: Dong Bo Trang Thai Doc/Chua Doc Tin Nhan Sang Server Khi User Cuon Qua Tin Nhan Trong Chat App",
     "content": "function onMessageVisible(messageId) { messageReadStatus.set(messageId, true); syncReadStatusToServer(messageId) } — syncReadStatusToServer() la async (goi API) khong duoc await — ham hoan tat ngay lap tuc, cap nhat UI local truoc, nhung neu user vuot ra khoi man hinh chat qua nhanh (network request bi huy do component unmount hoac app chuyen background), trang thai 'da doc' khong duoc dong bo len server, nguoi gui van thay tin nhan 'chua doc' du nguoi nhan da thuc su xem roi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-007", "title": "Missing Await: Giai Phong Slot Dat Cho Tam Thoi (Reservation Hold) Khi User Huy Thanh Toan Giua Chung",
     "content": "function cancelCheckout(reservationId) { releaseReservationHold(reservationId); redirectToHomePage() } — releaseReservationHold() la async (cap nhat database de tra lai slot cho nguoi khac dat) khong duoc await — redirectToHomePage() chay ngay lap tuc, neu qua trinh chuyen trang lam gian doan JavaScript execution context (vi du single-page app dieu huong hard reload), Promise cua releaseReservationHold co the khong bao gio hoan tat, slot van bi giu 'ma' (khong ai dat duoc) cho toi khi timeout tu nhien cua he thong reservation.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-008", "title": "Missing Await: Cap Nhat Chi So Tin Cay (Trust Score) Nguoi Ban Sau Khi Hoan Tat Giao Dich Marketplace",
     "content": "async function completeTransaction(txId) { await db.transactions.update(txId, { status: 'completed' }); updateSellerTrustScore(txId); return { success: true } } — updateSellerTrustScore() la async (tinh toan phuc tap dua tren lich su giao dich) khong duoc await — API tra ve thanh cong ngay ca khi trust score chua duoc cap nhat, neu request tiep theo cua buyer khac truy van trust score cua seller nay NGAY SAU giao dich vua hoan tat, co the thay diem cu chua phan anh dung giao dich thanh cong vua roi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-009", "title": "Missing Await: Thu Hoi Quyen Truy Cap Tai Lieu Chia Se Khi Owner Xoa Nguoi Duoc Chia Se Trong Ung Dung Cong Tac",
     "content": "function removeCollaborator(docId, userId) { updateDocPermissions(docId, userId, 'removed'); showSuccessToast('Collaborator removed') } — updateDocPermissions() la async (cap nhat ACL trong database phan quyen) khong duoc await — toast 'da xoa thanh cong' hien thi ngay lap tuc, trong khoang thoi gian ACL chua thuc su duoc cap nhat, nguoi vua bi xoa quyen VAN CO THE tiep tuc chinh sua tai lieu neu ho dang mo tai lieu do va gui request edit dung luc do — lo hong bao mat ngan nhung co that trong ung dung cong tac tai lieu.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-010", "title": "Missing Await: Cap Nhat So Du Vi Diem Thuong (Loyalty Points) Sau Khi Ap Dung Ma Khuyen Mai",
     "content": "function applyPromoCode(userId, code) { const discount = validatePromoCode(code); deductLoyaltyPoints(userId, discount.pointCost); return { discount } } — deductLoyaltyPoints() la async (tru diem trong database) khong duoc await — ham tra ve discount ngay lap tuc du diem chua chac chan da bi tru, neu user ngay lap tuc kiem tra so du diem o 1 tab/request khac, co the thay so diem CU (chua bi tru), tao ra khoang thoi gian nho ma so du diem hien thi khong khop voi trang thai thuc te da xu ly.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-011", "title": "Missing Await: Ghi Nhan Lich Su Xem Video Trong Nen Tang Streaming Khi User Tam Dung Hoac Chuyen Video",
     "content": "function onVideoPause(videoId, currentTime) { saveWatchProgress(videoId, currentTime); showPauseOverlay() } — saveWatchProgress() la async (goi API luu tien do xem) khong duoc await — overlay hien thi ngay lap tuc, neu user dong tab/app rat nhanh sau khi tam dung (hanh vi pho bien thuc te khi xem video), request luu tien do co the bi huy giua chung do trang bi dong, lan sau mo lai video, user phai xem lai tu dau thay vi tiep tuc tu vi tri da tam dung.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-012", "title": "Missing Await: Vo Hieu Hoa Ma Giam Gia Single-Use Sau Khi Ap Dung Thanh Cong Trong Flow Thanh Toan",
     "content": "async function checkout(cart, promoCode) { const order = await createOrder(cart); if (promoCode) invalidatePromoCode(promoCode); return order } — invalidatePromoCode() la async (danh dau ma da su dung trong database) khong duoc await — checkout() tra ve order thanh cong ngay lap tuc, neu invalidatePromoCode() that bai am tham (unhandled rejection) hoac chua chay xong, cung ma promo do co the duoc su dung lai boi cung user hoac user khac trong khoang thoi gian truoc khi invalidation thuc su hoan tat — lo hong gay thiet hai tai chinh voi ma giam gia chi-dung-mot-lan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-013", "title": "Missing Await: Gui Su Kien Webhook Ra Ngoai Khi Trang Thai Don Hang Thay Doi Trong He Thong E-commerce",
     "content": "async function updateOrderStatus(orderId, newStatus) { await db.orders.update(orderId, { status: newStatus }); triggerWebhooksForEvent('order.status_changed', { orderId, newStatus }); return { updated: true } } — triggerWebhooksForEvent() la async (gui HTTP request den tat ca webhook URL da dang ky cua merchant) khong duoc await — ham tra ve 'updated: true' ngay lap tuc, cac webhook con dang gui ngam va co the that bai am tham (timeout, DNS loi) ma khong ai theo doi lai — merchant tich hop webhook khong nhan duoc thong bao thay doi trang thai don hang quan trong ma khong co dau hieu loi nao duoc ghi nhan trong he thong chinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-014", "title": "Missing Await: Cap Nhat Vi Tri Tai Xe Realtime Trong Ung Dung Goi Xe Sau Khi Nhan Toa Do GPS Moi",
     "content": "function onLocationUpdate(driverId, coords) { updateDriverLocationInDb(driverId, coords); broadcastLocationToPassengers(driverId, coords) } — updateDriverLocationInDb() la async khong duoc await, nhung broadcastLocationToPassengers() chay ngay sau do — hanh khach nhan duoc vi tri MOI qua broadcast (dung), nhung neu bat ky request nao khac (vi du API tinh khoang cach den diem don) doc lai vi tri tu database NGAY LUC do, co the doc phai vi tri CU (chua kip cap nhat), gay sai lech uoc tinh thoi gian den don khach.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
    {"id": "js-b8-pna-015", "title": "Missing Await: Dong Bo Trang Thai Hoan Thanh Bai Tap Ve Server Trong Ung Dung Hoc Truc Tuyen Khi Hoc Sinh Nop Bai",
     "content": "function submitAssignment(studentId, assignmentId, answers) { gradeSubmission(answers); markAssignmentComplete(studentId, assignmentId); showCompletionAnimation() } — ca gradeSubmission() (co the async neu goi service cham diem tu dong) va markAssignmentComplete() (ghi database) khong duoc await — showCompletionAnimation() chay ngay lap tuc bao hoc sinh 'da hoan thanh', du diem so va trang thai chua chac chan da duoc luu, neu co loi mang giua chung, hoc sinh thay animation hoan thanh nhung giao vien lai khong thay bai nop trong danh sach cham diem.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch8, dua tren mo ta promise_no_await)", "url": "", "pattern_ids": ["promise_no_await"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
