"""
AI2 — batch 7 mo rong KB: viet tay 15 doc/pattern cho 3 pattern dang o muc 17
(concurrent_write_array, context_loss_this, buffer_leak). Moi doc la 1 tinh
huong code CU THE khac nhau that su, khac ca cac doc round1/round2 da co cung
pattern (khong lap lai vi du/co che da dung).

Chay: python add_batch7_docs.py
"""
import json
from pathlib import Path

KB_PATH = Path(__file__).parent.parent / "knowledge_base.json"

NEW_DOCS = [
    # ============= CONCURRENT_WRITE_ARRAY (15 doc) =============
    {"id": "js-b7-cwa-001", "title": "Concurrent Write: Nhieu Player Cung Ghi Vi Tri Vao Mang State Game Server Authoritative",
     "content": "let playerPositions = []; socket.on('move', (data) => { const idx = playerPositions.findIndex(p => p.id === data.id); if (idx === -1) playerPositions.push(data); else playerPositions[idx] = data }) — nhieu client gui update vi tri gan nhu dong thoi (game multiplayer realtime) — thao tac findIndex() roi push/gan lai khong atomic, neu 2 player MOI (chua co trong mang) gui move cung luc, ca 2 co the cung nhan findIndex() = -1 va ca 2 cung push, tao ra entry trung lap cho cung 1 player thay vi 1 entry duy nhat duoc cap nhat.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-002", "title": "Concurrent Write: Batch Job Nightly Va User Action Realtime Cung Ghi Vao Mang Danh Sach Task Can Xu Ly",
     "content": "let taskQueue = []; cron.schedule('0 0 * * *', () => { const overdueItems = getOverdueItems(); taskQueue.push(...overdueItems) }); app.post('/task/urgent', (req, res) => { taskQueue.push(req.body); res.sendStatus(200) }) — cron job dem hang tram item vao mang cung luc voi push(...overdueItems), neu 1 request urgent den DUNG luc cron dang thuc thi doan spread nay (trong JS don luong thi an toan, nhung neu logic duoc port sang co gioi han thoi gian cat lat — nhu Node.js worker co timeout — co the bi ngat giua chung), gay mat 1 phan du lieu dang duoc them vao.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-003", "title": "Concurrent Write: Nhieu Tab Trinh Duyet Cung Ghi Vao Mang Recently Viewed Products Qua BroadcastChannel",
     "content": "const channel = new BroadcastChannel('recently-viewed'); let recentlyViewed = JSON.parse(sessionStorage.getItem('rv') || '[]'); function addToRecentlyViewed(productId) { recentlyViewed.push(productId); sessionStorage.setItem('rv', JSON.stringify(recentlyViewed)) } channel.onmessage = (e) => { recentlyViewed.push(e.data) } — 2 tab cung mo 1 san pham gan nhu dong thoi, moi tab tu push vao mang cuc bo cua no ROI gui qua BroadcastChannel cho tab kia — tab nhan message lai push THEM 1 lan nua (khong kiem tra trung), dan den mang recentlyViewed co phan tu trung lap sau vai lan qua lai giua cac tab.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-004", "title": "Concurrent Write: Nhieu Microservice Cung Ghi Su Kien Vao Mang Event Log Chia Se Qua Shared Memory Cache Layer",
     "content": "async function appendEvent(event) { const events = JSON.parse(await memcached.get('event-log') || '[]'); events.push(event); await memcached.set('event-log', JSON.stringify(events)) } — nhieu service (auth-service, order-service, payment-service) cung goi ham nay de ghi log su kien tap trung vao memcached — memcached khong dam bao atomic cho pattern get-modify-set nay, 2 service ghi gan nhu dong thoi se ghi de len nhau, mat log cua 1 trong 2 service (nguy hiem cho audit trail lien quan bao mat/tai chinh).",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-005", "title": "Concurrent Write: Nhieu Sensor IoT Gui Du Lieu Dong Thoi Ghi Vao Mang Buffer Truoc Khi Flush Dinh Ky",
     "content": "let sensorBuffer = []; mqttClient.on('message', (topic, payload) => { sensorBuffer.push(JSON.parse(payload.toString())) }); setInterval(() => { flushToDatabase(sensorBuffer); sensorBuffer = [] }, 5000) — neu setInterval dang thuc thi flushToDatabase() (async, mat thoi gian) va bien sensorBuffer da duoc gan lai '= []' o dong tiep theo TRUOC KHI flushToDatabase() thuc su hoan tat xu ly du lieu cu, cac message MQTT den DUNG luc do bi push vao mang moi (rong) — nhung du lieu nay co the bi flush lan sau ma khong duoc dam bao thu tu dung, hoac tham chi bi flushToDatabase() cu (dang giu tham chieu mang cu) bo lo hoan toan.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-006", "title": "Concurrent Write: Multiple Tab Cung Ghi Vao IndexedDB Object Store Mang Draft Comments Chua Gui",
     "content": "async function saveDraft(comment) { const tx = db.transaction('drafts', 'readwrite'); const store = tx.objectStore('drafts'); const existing = await store.get('draftList'); const list = existing ? existing.items : []; list.push(comment); await store.put({ id: 'draftList', items: list }) } — 2 tab cung goi saveDraft() gan nhu dong thoi (du IndexedDB co transaction, nhung logic doc-sua-ghi TRONG code nay khong dam bao atomic o cap ung dung — get() va put() la 2 buoc rieng, transaction chi bao ve tung buoc khong bao ve toan bo chu trinh) — 1 trong 2 draft co the bi mat neu 2 transaction xen ke o dung thoi diem.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-007", "title": "Concurrent Write: Nhieu Voter Bam Vote Dong Thoi Ghi Vao Mang Danh Sach Nguoi Da Vote Cho Poll",
     "content": "let votedUsers = []; app.post('/poll/:id/vote', async (req, res) => { const poll = await getPoll(req.params.id); if (votedUsers.includes(req.user.id)) return res.status(400).json({ error: 'already voted' }); votedUsers.push(req.user.id); await incrementVoteCount(req.params.id, req.body.option); res.sendStatus(200) }) — 1 user bam vote 2 lan rat nhanh (double-click) hoac dung 2 tab — thao tac kiem tra includes() roi push khong atomic, ca 2 request gan nhu dong thoi cung khong thay user trong mang votedUsers (vi ca 2 doc truoc khi ben kia kip ghi), ca 2 deu qua duoc kiem tra va vote count bi tang 2 lan cho cung 1 user.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-008", "title": "Concurrent Write: Nhieu Producer Kafka Consumer Group Cung Ghi Vao Mang Dead Letter Queue Trong Memory Truoc Khi Persist",
     "content": "let dlqBuffer = []; consumer.run({ eachMessage: async ({ message }) => { try { await processMessage(message) } catch (e) { dlqBuffer.push({ message, error: e.message }) } } }) — voi consumer group co nhieu partition duoc xu ly song song boi cung 1 consumer instance (Kafka cho phep nhieu partition xu ly dong thoi trong cung process), moi partition co the push loi vao dlqBuffer gan nhu dong thoi — trong Node.js don luong day thuc te an toan (khong mat data), NHUNG neu logic nay duoc scale ra nhieu worker_threads de tang throughput xu ly message, tinh an toan nay se mat.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-009", "title": "Concurrent Write: Nhieu API Gateway Instance Cung Ghi Vao Mang Circuit Breaker State Chia Se Qua File Local",
     "content": "function recordFailure(serviceId) { const state = JSON.parse(fs.readFileSync('./circuit-state.json', 'utf8')); state[serviceId] = state[serviceId] || []; state[serviceId].push(Date.now()); fs.writeFileSync('./circuit-state.json', JSON.stringify(state)) } — neu app duoc scale qua cluster module (nhieu worker process tren cung may), moi worker doc/ghi file nay doc lap — 2 worker ghi nhan loi gan nhu dong thoi cho cung serviceId co the ghi de len nhau (doc truoc khi ben kia ghi xong), circuit breaker dem thieu so loi thuc te, co the khong mo circuit du service that su da that bai vuot nguong.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-010", "title": "Concurrent Write: Nhieu Component React Cung Ghi Vao Mang Global Toast Notification Queue Qua Context Khong Dung Reducer",
     "content": "let toastQueue = []; const ToastContext = createContext(); function showToast(msg) { toastQueue.push(msg); forceRerender() } // nhieu component goi showToast() lien tiep trong cung 1 render cycle (vi du useEffect cua nhieu component con chay gan nhu dong thoi khi trang load) — do React co the batch nhieu state update, cac lan push() vao mang MODULE-LEVEL (khong phai React state) co the bi ghi de neu forceRerender() gay re-render doc lai gia tri ban dau tu closure cu truoc do, mat 1 so toast message da duoc them vao.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-011", "title": "Concurrent Write: Nhieu Instance Serverless Function Cung Ghi Vao Mang Idempotency Keys Da Xu Ly Trong DynamoDB Khong Dung Condition Expression",
     "content": "async function processWithIdempotency(key, handler) { const record = await dynamoClient.get({ TableName: 'idempotency', Key: { key } }); if (record.Item) return record.Item.result; const result = await handler(); await dynamoClient.put({ TableName: 'idempotency', Item: { key, result } }); return result } — 2 Lambda invocation cho CUNG 1 idempotency key (vi du do API Gateway retry) gan nhu dong thoi — ca 2 cung doc thay record.Item khong ton tai (chua co ai ghi), ca 2 cung goi handler() va ghi ket qua — mat tinh idempotent thuc su, handler() (co the la thao tac tinh phi/gui email) chay 2 lan thay vi 1, can dung ConditionExpression 'attribute_not_exists' khi put() de dam bao atomic that su.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-012", "title": "Concurrent Write: Nhieu Test Song Song Trong Jest workerIdleMemoryLimit Cung Ghi Vao Mang Global Coverage Report File",
     "content": "afterEach(() => { const report = JSON.parse(fs.readFileSync('./coverage-custom.json', 'utf8')); report.testsRun.push(expect.getState().currentTestName); fs.writeFileSync('./coverage-custom.json', JSON.stringify(report)) }) — Jest chay test song song qua nhieu worker process (--maxWorkers), moi worker doc-sua-ghi CUNG 1 file coverage-custom.json doc lap — cac worker ghi de len nhau lien tuc, file coverage cuoi cung chi phan anh 1 phan test that su da chay (tu worker ghi cuoi cung), khong dai dien cho toan bo test suite.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-013", "title": "Concurrent Write: Nhieu Webhook Retry Task Song Song Cung Ghi Vao Mang Retry History Cua Cung 1 Webhook Subscription",
     "content": "async function retryWebhook(subscriptionId, attempt) { const sub = await db.subscriptions.findById(subscriptionId); sub.retryHistory.push({ attempt, timestamp: Date.now() }); await db.subscriptions.update(subscriptionId, sub) } — he thong retry co the trigger nhieu lan retry cho CUNG 1 subscription gan nhu dong thoi (vi du do backoff logic bi tinh sai o noi khac, gay duplicate trigger) — moi lan retry doc sub cu (voi retryHistory chua co entry moi nhat tu lan retry khac dang chay song song), ghi de mat lich su retry, khien viec debug 'webhook nay da retry bao nhieu lan' cho ra so lieu sai.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-014", "title": "Concurrent Write: Nhieu Browser Extension Content Script Instance Cung Ghi Vao Mang Highlighted Elements Qua chrome.storage",
     "content": "async function addHighlight(elementId) { const data = await chrome.storage.local.get('highlights'); const highlights = data.highlights || []; highlights.push(elementId); await chrome.storage.local.set({ highlights }) } — neu user mo nhieu tab cung 1 website VA extension chay content script rieng tren moi tab — 2 tab cung goi addHighlight() gan nhu dong thoi (vi du user highlight text tren 2 tab cung luc), moi tab doc chrome.storage TRUOC khi tab kia kip ghi, dan den highlight cua 1 trong 2 tab bi mat khi set() ghi de.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},
    {"id": "js-b7-cwa-015", "title": "Concurrent Write: Nhieu CI Job Song Song Trong Matrix Build Cung Ghi Vao Mang Test Results Summary File Qua GitHub Actions Artifact",
     "content": "// script chay trong moi job cua matrix build: const summary = JSON.parse(fs.readFileSync('./summary.json', 'utf8')); summary.results.push({ os: process.env.MATRIX_OS, passed: testsPassed }); fs.writeFileSync('./summary.json', JSON.stringify(summary)) — neu cac job matrix (chay tren nhieu OS khac nhau: ubuntu, windows, macos) VO TINH deu ghi vao CUNG 1 artifact duoc chia se qua volume mount thay vi moi job co artifact rieng — cac job chay song song se ghi de ket qua cua nhau, summary.json cuoi cung chi con ket qua cua job ghi sau cung thay vi tong hop ca 3 OS.",
     "language": "javascript", "category": "race-conditions",
     "source": "Generated (batch7, dua tren mo ta concurrent_write_array)", "url": "", "pattern_ids": ["concurrent_write_array"]},

    # ============= CONTEXT_LOSS_THIS (15 doc) =============
    {"id": "js-b7-clt-001", "title": "Context Loss: Koa.js Middleware Class Method Duoc Dang Ky Truc Tiep Vao app.use() Khong Bind",
     "content": "class RequestLogger { constructor(logStream) { this.logStream = logStream } middleware(ctx, next) { this.logStream.write(`${ctx.method} ${ctx.url}\\n`); return next() } } const logger = new RequestLogger(stream); app.use(logger.middleware) — Koa goi middleware nhu 1 function doc lap, 'this' ben trong middleware() khong con la RequestLogger instance, this.logStream la undefined, moi request nem TypeError ngay o middleware dau tien cua chuoi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-002", "title": "Context Loss: Ham Debounce/Throttle Custom Wrap Method Cua Class Ma Khong Preserve This",
     "content": "function throttle(fn, ms) { let last = 0; return function(...args) { const now = Date.now(); if (now - last >= ms) { last = now; fn(...args) } } } class ScrollTracker { constructor() { this.position = 0; this.onScroll = throttle(this.handleScroll, 100) } handleScroll(e) { this.position = e.target.scrollTop } } — throttle() tra ve 1 function moi (khong phai arrow function, ma la 'function' thuong), khi function nay duoc goi qua window.addEventListener('scroll', tracker.onScroll), 'this' ben trong fn(...args) — tuc handleScroll — khong con la ScrollTracker instance, this.position nem loi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-003", "title": "Context Loss: NestJS Service Method Duoc Truyen Lam Callback Cho Thu Vien Scheduler Ben Ngoai NestJS DI",
     "content": "@Injectable() class ReportService { constructor(private db: DbService) {} async generateDailyReport() { const data = await this.db.query(...); this.saveReport(data) } } // trong module setup (ngoai NestJS lifecycle): const service = new ReportService(dbInstance); nodeSchedule.scheduleJob('0 0 * * *', service.generateDailyReport) — truyen service.generateDailyReport truc tiep cho scheduler ben ngoai he thong Dependency Injection cua NestJS (bo qua decorator @Cron chinh thuc) tach method khoi instance, 'this' mat, this.db la undefined khi job chay.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-004", "title": "Context Loss: Array.prototype.find Voi Predicate Method Cua Class So Sanh Thuoc Tinh Instance",
     "content": "class PermissionChecker { constructor(userRole) { this.userRole = userRole } hasAccess(resource) { return resource.requiredRole === this.userRole } findAccessible(resources) { return resources.find(this.hasAccess) } } — findAccessible() truyen this.hasAccess vao find() ma khong bind — Array.prototype.find goi predicate nhu function doc lap, ben trong hasAccess() 'this' khong con la PermissionChecker instance, this.userRole la undefined, so sanh 'requiredRole === undefined' luon false, find() tra ve undefined cho moi truong hop dung ra phai tim thay resource hop le.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-005", "title": "Context Loss: Svelte Component Method Duoc Truyen Lam Prop Callback Xuong Component Con Ma Khong Bind",
     "content": "<script> class FormValidator { constructor() { this.errors = {} } validateField(name, value) { if (!value) this.errors[name] = 'required' } } const validator = new FormValidator(); </script> <ChildInput onValidate={validator.validateField} /> — truyen validator.validateField truc tiep lam prop callback xuong component con — khi component con goi callback nay (nhu 1 function doc lap thong thuong), 'this' ben trong validateField() khong con la FormValidator instance, this.errors la undefined, gay loi khi gan gia tri vao property cua undefined.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-006", "title": "Context Loss: RxJS Observable Pipe Operator Custom Su Dung Method Cua Class Lam Callback Cho map()",
     "content": "class DataTransformer { constructor(multiplier) { this.multiplier = multiplier } transform(value) { return value * this.multiplier } } const transformer = new DataTransformer(2); source$.pipe(map(transformer.transform)).subscribe(console.log) — truyen transformer.transform truc tiep vao operator map() cua RxJS — map() goi callback nhu function doc lap cho moi gia tri phat ra tu Observable, 'this' ben trong transform() khong con la DataTransformer instance, this.multiplier la undefined, ket qua tra ve NaN cho moi gia tri thay vi gia tri da nhan voi multiplier.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-007", "title": "Context Loss: Ham Memoize Custom Wrap Method Class Nhung Cache Key Dua Vao This Ma Khong Con Ton Tai",
     "content": "function memoize(fn) { const cache = new Map(); return function(...args) { const key = JSON.stringify(args) + this.id; if (cache.has(key)) return cache.get(key); const result = fn.apply(this, args); cache.set(key, result); return result } } class Calculator { constructor(id) { this.id = id } compute(x) { return x * 2 } } const calc = new Calculator('A'); const memoized = memoize(calc.compute); memoized(5) — memoize() tra ve 1 function thuong (khong phai arrow) co dung 'this' de tao cache key, nhung khi memoized(5) duoc goi TRUC TIEP (khong qua calc.memoized(5)), 'this' ben trong la undefined, this.id nem TypeError ngay khi tinh cache key, truoc ca khi kip goi fn.apply().",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-008", "title": "Context Loss: Cytoscape.js Graph Event Handler Su Dung Method Cua Class Quan Ly State Do Thi",
     "content": "class GraphManager { constructor(cy) { this.cy = cy; this.selectedNodes = []; this.cy.on('tap', 'node', this.handleNodeTap) } handleNodeTap(event) { this.selectedNodes.push(event.target.id()) } } — dang ky this.handleNodeTap truc tiep cho su kien 'tap' cua thu vien Cytoscape.js (visualize do thi) ma khong bind — thu vien goi handler voi 'this' tro ve context rieng cua no (thuong la element duoc click, khong phai GraphManager instance), this.selectedNodes.push() nem loi vi 'this' sai hoan toan.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-009", "title": "Context Loss: Bull Queue Job Processor Method Cua Class Duoc Dang Ky Truc Tiep Cho queue.process()",
     "content": "class OrderProcessor { constructor(emailService) { this.emailService = emailService } async processOrderJob(job) { const order = job.data; await this.emailService.sendConfirmation(order) } } const processor = new OrderProcessor(emailSvc); orderQueue.process(processor.processOrderJob) — dang ky processor.processOrderJob truc tiep cho Bull queue ma khong bind — Bull goi ham nay nhu function doc lap moi khi co job moi, 'this' ben trong khong con la OrderProcessor instance, this.emailService la undefined, moi job trong queue that bai voi loi giong nhau.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-010", "title": "Context Loss: D3.js Data Binding Su Dung Method Cua Class De Tinh Toan Vi Tri Element SVG",
     "content": "class ChartRenderer { constructor(scale) { this.scale = scale } calculateX(d) { return this.scale(d.value) } render(data) { d3.select('svg').selectAll('circle').data(data).attr('cx', this.calculateX) } } — truyen this.calculateX truc tiep cho .attr() cua D3.js — D3 goi ham nay voi 'this' tro ve DOM element dang duoc bind du lieu (theo convention cua D3), khong phai ChartRenderer instance, this.scale la undefined ben trong calculateX(), gay loi khi render bieu do, khong 1 circle nao duoc dat dung vi tri.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-011", "title": "Context Loss: Express Error Middleware Class Wrapper Method Bi Mat This Khi Dang Ky Qua app.use(errorHandler.handle)",
     "content": "class ErrorHandler { constructor(logger) { this.logger = logger } handle(err, req, res, next) { this.logger.error(err); res.status(500).json({ error: 'Internal error' }) } } const errorHandler = new ErrorHandler(loggerInstance); app.use(errorHandler.handle) — dang ky errorHandler.handle truc tiep (4 tham so, Express nhan dien la error middleware) ma khong bind — khi co loi xay ra o middleware truoc do, Express goi handle() nhu function doc lap, this.logger la undefined, viec xu ly loi lai nem ra 1 loi moi (TypeError) thay vi log va tra response loi nhu du dinh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-012", "title": "Context Loss: Vitest Custom Matcher Function Su Dung Method Cua Class Helper De So Sanh Gia Tri",
     "content": "class ToleranceComparator { constructor(epsilon) { this.epsilon = epsilon } isClose(a, b) { return Math.abs(a - b) < this.epsilon } } const comparator = new ToleranceComparator(0.001); expect.extend({ toBeCloseWithTolerance: comparator.isClose }) — dang ky comparator.isClose truc tiep lam custom matcher cho Vitest ma khong bind — Vitest goi matcher function voi 'this' tro ve context matcher rieng cua no (chua cac helper nhu this.isNot), khong phai ToleranceComparator instance, this.epsilon la undefined, moi lan dung matcher deu nem loi thay vi so sanh gia tri.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-013", "title": "Context Loss: Three.js Animation Loop Su Dung Method Cua Class Scene Manager Truyen Cho requestAnimationFrame",
     "content": "class SceneManager { constructor(scene, camera, renderer) { this.scene = scene; this.camera = camera; this.renderer = renderer } animate() { requestAnimationFrame(this.animate); this.renderer.render(this.scene, this.camera) } } — this.animate goi de quy chinh no qua requestAnimationFrame ma khong bind — lan goi DAU TIEN (tu code khoi tao ben ngoai goi sceneManager.animate() dung cach) co the chay dung, nhung lan goi DE QUY BEN TRONG (this.animate trong requestAnimationFrame) mat 'this', cac frame animation sau lan dau deu that bai voi this.renderer la undefined.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-014", "title": "Context Loss: Commander.js CLI Action Handler Su Dung Method Cua Class Config Manager",
     "content": "class ConfigManager { constructor(configPath) { this.configPath = configPath } saveConfig(options) { fs.writeFileSync(this.configPath, JSON.stringify(options)) } } const manager = new ConfigManager('./app.config.json'); program.command('config').action(manager.saveConfig) — dang ky manager.saveConfig truc tiep cho Commander.js .action() ma khong bind — khi user chay lenh CLI 'config', Commander goi ham nay nhu function doc lap voi cac tham so tu CLI, 'this' ben trong khong con la ConfigManager instance, this.configPath la undefined, fs.writeFileSync() nem loi ngay khi user chay lenh.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},
    {"id": "js-b7-clt-015", "title": "Context Loss: Zod Custom Refine Function Su Dung Method Cua Class Business Rule Validator",
     "content": "class BusinessRuleValidator { constructor(minAge) { this.minAge = minAge } isValidAge(age) { return age >= this.minAge } } const validator = new BusinessRuleValidator(18); const schema = z.number().refine(validator.isValidAge, { message: 'too young' }) — truyen validator.isValidAge truc tiep vao .refine() cua Zod ma khong bind — Zod goi ham refine nhu function doc lap khi validate schema, 'this' ben trong isValidAge() khong con la BusinessRuleValidator instance, this.minAge la undefined, so sanh 'age >= undefined' luon false, moi gia tri hop le deu bi tu choi sai.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta context_loss_this)", "url": "", "pattern_ids": ["context_loss_this"]},

    # ============= BUFFER_LEAK (15 doc) =============
    {"id": "js-b7-bl-001", "title": "Buffer Leak: HTTP/2 Server Push Stream Khong Duoc Close Khi Client Tu Choi Push",
     "content": "http2Server.on('stream', (stream, headers) => { const pushStream = stream.pushStream({ ':path': '/style.css' }, (err, pushStream) => { fs.createReadStream('./style.css').pipe(pushStream) }) }) — neu client tu choi server push (gui RST_STREAM), pushStream co the da duoc tao va bat dau pipe du lieu vao no — khong co error handler de bat truong hop nay va goi destroy(), ReadStream nguon van tiep tuc doc file va co ReadStream buffer trong memory du khong con noi nao de gui du lieu di.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-002", "title": "Buffer Leak: Server-Side gRPC Streaming Response Khong Duoc End Khi Loi Xay Ra Giua Chung Gui Data",
     "content": "function streamLargeDataset(call) { const cursor = db.collection('big_data').find().stream(); cursor.on('data', (doc) => { if (!call.write(transform(doc))) { cursor.pause() } }); cursor.on('error', (err) => { call.emit('error', err) }) } — handler 'error' cua cursor chi emit loi cho call nhung khong goi cursor.destroy() hay call.end() — neu cursor gap loi giua chung dang doc, database cursor van con mo o server, va gRPC call stream (call) cung khong duoc dong dung cach, tich luy qua thoi gian voi nhieu request loi gay leak ca 2 phia.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-003", "title": "Buffer Leak: Ham Xu Ly Nen File Tar.gz Khong Destroy Cac Stream Trung Gian Khi 1 Buoc Trong Chuoi Pipe That Bai",
     "content": "function createTarball(sourceDir, outputPath) { const output = fs.createWriteStream(outputPath); const archive = archiver('tar', { gzip: true }); archive.pipe(output); archive.directory(sourceDir, false); archive.finalize() } — neu sourceDir chua file voi quyen truy cap bi tu choi giua qua trinh nen, archive emit 'error' nhung khong co listener nao bat loi nay de goi archive.abort() va output.destroy() — output WriteStream van mo cho du archive da that bai, giu file descriptor lam viec output khong bao gio duoc dong dung cach.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-004", "title": "Buffer Leak: WebRTC Data Channel Khong Duoc Close Khi Peer Connection Bi Ngat Ket Noi Dot Ngot",
     "content": "const dataChannel = peerConnection.createDataChannel('chat'); dataChannel.onmessage = (event) => { messageBuffer.push(event.data) } — khong co xu ly cho su kien 'iceconnectionstatechange' de dong dataChannel khi peer mat ket noi (vi du dong app dot ngot, mat mang) — dataChannel va cac buffer message lien quan van ton tai trong memory trinh duyet cho toi khi trang duoc reload thu cong, gay tich luy memory neu app cho phep nhieu ket noi WebRTC lien tuc (vi du video call app) ma khong reload trang.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-005", "title": "Buffer Leak: Ham Doc Metadata EXIF Tu Anh Khong Giai Phong Buffer Khi Anh Bi Corrupt",
     "content": "function extractExifData(imagePath) { const buffer = fs.readFileSync(imagePath); try { return exifReader(buffer) } catch (e) { console.error('Corrupt image:', imagePath); return null } } — readFileSync() (khong phai stream, doc toan bo vao memory) doc file vao 'buffer' truoc khi thu parse — voi anh lon bi corrupt (parse that bai lien tuc), buffer da doc van ton tai trong bo nho local scope cho den khi ham ket thuc va GC don dep, nhung neu ham nay duoc goi trong vong lap xu ly hang tram anh lien tiep rat nhanh, memory pressure tang cao truoc khi GC kip chay.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-006", "title": "Buffer Leak: MediaRecorder API Khong Duoc Stop Khi Component React Ghi Am Bi Unmount Giua Chung",
     "content": "useEffect(() => { const recorder = new MediaRecorder(stream); recorder.start(); recorder.ondataavailable = (e) => chunks.push(e.data); return () => { /* thieu recorder.stop() */ } }, []) — cleanup function cua useEffect khong goi recorder.stop() truoc khi component unmount — MediaRecorder va MediaStream lien quan (bao gom truy cap microphone/camera cua browser) van tiep tuc hoat dong ngam sau khi component da bi go khoi UI, giu tai nguyen phan cung (microphone) bi chiem dung va buffer audio/video tiep tuc tich luy trong memory khong ai su dung.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-007", "title": "Buffer Leak: Named Pipe (FIFO) Trong Linux Khong Duoc Close File Descriptor Sau Khi Doc Xong 1 Lan",
     "content": "function readFromNamedPipe(pipePath) { const fd = fs.openSync(pipePath, 'r'); const buffer = Buffer.alloc(1024); fs.readSync(fd, buffer, 0, 1024, 0); return buffer.toString() } — fs.openSync() mo file descriptor cho named pipe nhung khong bao gio goi fs.closeSync(fd) sau khi doc xong — moi lan ham nay duoc goi (vi du de poll du lieu tu 1 process khac ghi vao pipe), 1 file descriptor moi bi leak, sau nhieu lan goi se vuot qua gioi han FD cua he thong (EMFILE), dac biet nghiem trong vi named pipe thuong duoc poll lien tuc.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-008", "title": "Buffer Leak: Audio Context Web Audio API Khong Duoc Close Khi User Chuyen Bai Hat Lien Tuc Nhanh",
     "content": "function playTrack(url) { const audioContext = new AudioContext(); fetch(url).then(r => r.arrayBuffer()).then(buf => audioContext.decodeAudioData(buf)).then(decoded => { const source = audioContext.createBufferSource(); source.buffer = decoded; source.connect(audioContext.destination); source.start() }) } — moi lan user chuyen bai (goi lai playTrack()), 1 AudioContext MOI duoc tao ma khong dong AudioContext cu (audioContext.close()) — trinh duyet gioi han so luong AudioContext dong thoi (thuong khoang 4-6 tuy trinh duyet), sau vai lan chuyen bai nhanh se gap loi 'Cannot create more AudioContexts' hoac hieu suat giam manh do qua nhieu context dong thoi.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-009", "title": "Buffer Leak: Playwright Browser Context Khong Duoc Close Trong Test Suite Khi Test Fail Truoc Assertion Cuoi",
     "content": "test('checkout flow', async () => { const context = await browser.newContext(); const page = await context.newPage(); await page.goto(url); await page.click('#checkout'); expect(await page.textContent('.confirmation')).toBe('Success') }) — neu bat ky buoc nao truoc dong expect() throw loi (vi du click() timeout do element khong ton tai), test fail va ham ket thuc ngay lap tuc — khong co try/finally de goi context.close(), moi test fail de lai 1 browser context (voi cac page/tab ben trong) mo trong bo nho, chay CI voi nhieu test fail lien tuc co the lam browser process tieu ton RAM dang ke.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-010", "title": "Buffer Leak: SQLite Prepared Statement Khong Duoc Finalize Sau Khi Dung Xong Trong Vong Lap Query Nhieu Lan",
     "content": "function queryMultipleTimes(db, ids) { return ids.map(id => { const stmt = db.prepare('SELECT * FROM items WHERE id = ?'); return stmt.get(id) }) } — moi lan goi trong vong lap .map() tao 1 prepared statement MOI ma khong bao gio goi stmt.finalize() de giai phong tai nguyen cua no — voi mang ids lon (hang nghin phan tu), tich luy hang nghin prepared statement chua duoc finalize, giu tai nguyen SQLite driver noi bo, co the gay 'too many statements' hoac tieu ton memory dang ke thay vi tai su dung 1 statement duy nhat cho ca vong lap.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-011", "title": "Buffer Leak: Nodemailer SMTP Transport Pool Khong Duoc Close Khi Server Graceful Shutdown",
     "content": "const transporter = nodemailer.createTransport({ pool: true, host, auth }); process.on('SIGTERM', () => { server.close(() => process.exit(0)) }) — handler SIGTERM chi dong HTTP server nhung khong goi transporter.close() de dong SMTP connection pool — khi process nhan lenh restart/deploy (SIGTERM tu orchestrator nhu Kubernetes), cac ket noi SMTP dang giu trong pool khong duoc dong dung cach, co the gay canh bao 'connection reset' phia mail server hoac cham qua trinh graceful shutdown thuc te vi process cho cac handle nay tu dong het timeout.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-012", "title": "Buffer Leak: Ham Xu Ly Video Live Streaming RTMP Khong Cleanup FFmpeg Process Khi Nguon Stream Bi Gian Doan",
     "content": "function startTranscode(rtmpUrl, outputPath) { const ff = spawn('ffmpeg', ['-i', rtmpUrl, '-c:v', 'libx264', outputPath]); ff.stderr.on('data', (d) => console.log(d.toString())) } — neu nguon RTMP (nguoi stream) mat ket noi dot ngot giua chung, ffmpeg co the treo cho input moi thay vi thoat ngay — khong co timeout hoac giam sat 'process con khong hoat dong' de tu dong kill() no, process ffmpeg treo van chiem CPU/memory vo thoi han cho toi khi ai do thu cong phat hien va kill process.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-013", "title": "Buffer Leak: IntersectionObserver Trong Infinite Scroll Component Khong Duoc Disconnect Khi List Item Bi Xoa Khoi DOM",
     "content": "function observeItem(element, onVisible) { const observer = new IntersectionObserver((entries) => { if (entries[0].isIntersecting) onVisible() }); observer.observe(element) } // duoc goi cho MOI item trong danh sach infinite scroll — moi item tao 1 IntersectionObserver rieng nhung khong bao gio goi observer.disconnect() khi item bi xoa khoi DOM (do virtualization/filter) — voi danh sach scroll qua hang nghin item, tich luy hang nghin observer instance van con 'quan sat' cac element da khong con trong DOM, gay memory leak dan trong ung dung chay lau.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-014", "title": "Buffer Leak: gRPC Client Streaming Call Khong End() Khi Client Ngung Gui Du Lieu Do Loi Ung Dung",
     "content": "function uploadDataStream(records) { const call = grpcClient.uploadRecords((err, response) => { console.log('Upload complete') }); records.forEach(r => { if (isValid(r)) call.write(r) }); call.end() } — neu vong lap forEach throw loi giua chung (vi du 1 record gay loi khi validate trong isValid()), call.end() KHONG BAO GIO duoc goi (code dung lai o dong throw truoc khi den duoc call.end()) — gRPC client streaming call van mo cho, giu ket noi va buffer noi bo, phia server cung mai cho du lieu them khong bao gio den.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
    {"id": "js-b7-bl-015", "title": "Buffer Leak: Native Node.js Addon FileHandle Object Khong Duoc Close Khi Exception Xay Ra Truoc finally Block",
     "content": "async function processLargeFile(path) { const handle = await fs.promises.open(path, 'r'); const stats = await handle.stat(); if (stats.size > MAX_SIZE) throw new Error('file too large'); const buffer = Buffer.alloc(stats.size); await handle.read(buffer, 0, stats.size, 0); await handle.close(); return buffer } — nhanh throw new Error() khi kiem tra kich thuoc file that bai xay ra TRUOC khi handle.close() duoc goi (khong co try/finally bao boc) — FileHandle van mo, giu file descriptor cho toi khi GC don dep object nay (khong co gi dam bao thoi diem chinh xac), voi nhieu file lon bi tu choi lien tuc se tich luy file descriptor mo.",
     "language": "javascript", "category": "anti-patterns",
     "source": "Generated (batch7, dua tren mo ta buffer_leak)", "url": "", "pattern_ids": ["buffer_leak"]},
]


def main() -> None:
    docs = json.loads(KB_PATH.read_text(encoding="utf-8"))
    existing_ids = {d["id"] for d in docs}
    added = 0
    for nd in NEW_DOCS:
        if nd["id"] in existing_ids:
            print(f"SKIP (id da ton tai): {nd['id']}")
            continue
        docs.append(nd)
        added += 1
    KB_PATH.write_text(json.dumps(docs, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} doc moi. Tong KB: {len(docs)} doc.")


if __name__ == "__main__":
    main()
